### ISSUE TITLE
Scala Subquery should contain only 1 column

### ISSUE THREAD

**Issue by devgony** [gluesql/gluesql#1062]
Scala Subquery should contain only 1 column or throw error.
![image](https://user-images.githubusercontent.com/51254761/212463210-326115c3-9930-43e8-b552-14f84f76e41d.png)

Currently it returns the first column rather than throws error
```sql
gluesql> select (select 1, 2);
```
| (SELECT 1, 2) |
|---------------|
| 1             |

**Comment by ChobobDev** [comment]
I will work on this issue ,

Thanks in advance :)
