### ISSUE TITLE
Support user-level custom sql functions

### ISSUE THREAD

**Issue by pythonbrad** [gluesql/gluesql#1081]
### Description
The user should be able to register functions and use it as SQL functions.

### Example
```rs
fn function_say();
register_function("say", CustomFunction("say", function_say);
```
```sql
gluesql> SELECT SAY("Hello");
```

### Useful links
- [hibernate-sql-function-jpql-criteria-api-query](https://vladmihalcea.com/hibernate-sql-function-jpql-criteria-api-query)
- [registering-a-sql-function-with-jpa-and-hibernate](https://stackoverflow.com/questions/12346845/registering-a-sql-function-with-jpa-and-hibernate)
- [dynamically loading a library into memory at runtime](https://adventures.michaelfbryan.com/posts/plugins-in-rust)

**Comment by ever0de** [comment]
closed #1095
