### ISSUE TITLE
Change console.log in gluesql.js -> console.debug

### ISSUE THREAD

**Issue by LeoDog896** [gluesql/gluesql#1124]
I prefer to keep my browser logs clean with only what I need, but there is an unnecessary [initialization log](https://github.com/gluesql/gluesql/blob/64e4938952e77e43ba0a6e1bcabb662cfa638c67/pkg/javascript/web/src/lib.rs#L68) in gluesql.js. If this is used for debugging purposes, I do suggest to replace it with a start hook.

**Comment by panarch** [comment]
Thanks, how about this?
Rather than using `console.log`, replacing `log` to `debug` would be good way to resolve this because `console.debug` is not exposed to user by default.
Then, the issue can be .. we can summarize into "replace `console.log` to `console.debug`".

**Comment by LeoDog896** [comment]
Sounds good!
