### ISSUE TITLE
Fix misleadingmethod for type casting of UUID when its string

### ISSUE THREAD

**Issue by ChobobDev** [gluesql/gluesql#1129]
During my work on implementing the unsigned integer, I came across a conversion function that converts a string data type to a UUID data type. However, as we are now focusing on providing support for the u128 data type, I believe that converting string to u128 type with using parse_uuid should be deprecated.

AS-IS
```rust
impl TryFrom<&Value> for u128 {
    type Error = Error;

    fn try_from(v: &Value) -> Result<u128> {
        match v {
            Value::Uuid(value) => Ok(*value),
            Value::Str(value) => parse_uuid(value),
            Value::Inet(IpAddr::V6(v)) => Ok(u128::from(*v)),
            _ => Err(ValueError::ImpossibleCast.into()),
        }
    }
}
```

TO-BE
```rust
impl TryFrom<&Value> for u128 {
    type Error = Error;

    fn try_from(v: &Value) -> Result<u128> {
        match v {
            Value::Uuid(value) => Ok(*value),
            Value::Inet(IpAddr::V6(v)) => Ok(u128::from(*v)),
            Value::Str(value) => u128::from_str_radix(value, 10).map_err(|_| ValueError::FailedToParseNumber.into()),
            _ => Err(ValueError::ImpossibleCast.into()),
        }
    }
}
```

**Comment by pythonbrad** [comment]
Hello @ChobobDev, I think that this implementation consist only to convert a string representation of UUID to UUID. Does not work for any string.

**Comment by ChobobDev** [comment]
Hello @pythonbrad , I opned this issue while I was working on the different issue which is implementing the unsigned integer 
#1019 over here. And i have faced the problem with testing the string representation of UUID causes conflict when trying to convert the string that is unable to be casted in to u128 data type. Do you have any other possible solution for the following issue ?

**Comment by ChobobDev** [comment]
Oh, thank you for pointing this  out!
