### ISSUE TITLE
INSERT INTO SELECT Support

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#119]
Similar to my overall message in #118.

Example:
```sql
INSERT INTO
  table (
    valueA,
    valueB
  )
SELECT
  dataA,
  dataB
FROM
  otherTable
```

Is this functionality in progress? If not, how might I be able to help?

**Comment by panarch** [comment]
Currently this query is not supported yet. Anyone can participate on this issue, I'll leave it open with enhancement label.
This would be quite more simple than implementing indexing.

**Comment by KyGost** [comment]
Done in #120
