### ISSUE TITLE
Add support for DateTime type

### ISSUE THREAD

**Issue by Redblueflame** [gluesql/gluesql#121]
(Please note this is not really needed, but would be great on the way of more support of the SQL standard)

The DATETIME type allows for easy management of time data.

Things to do:

- [ ] Choose a way to store it in the database as raw data (The millis standard could be useful)
- [ ] Allow for timezone support
- [ ] Allow for operations on datetime type

All this could be helped with the inclusion of the [chrono crate](https://docs.rs/chrono/0.4.19/chrono/index.html)

**Comment by KyGost** [comment]
Any need for timezone support if it is just in millis?

**Comment by panarch** [comment]
* `DATE` and `TIMESTAMP` types #215 

I'll also add `INTERVAL` type soon.
