### ISSUE TITLE
The data stored in SledStorage will be lost

### ISSUE THREAD

**Issue by suncunxudsb** [gluesql/gluesql#1218]
The database connection code:
```rust
use gluesql::prelude::{Glue, SledStorage, Payload, Value as Gvalue};
use anyhow::Result;
use gluesql::core::result::Error;
use std::{sync::{Arc, Mutex}, path::PathBuf, env};
use lazy_static::lazy_static;

lazy_static! {
    static ref SHARED_DB: Arc<Mutex<Glue<SledStorage>>> = {  
        let mut storage = SledStorage::new(r"C:\Users\86136\data").unwrap();
        storage.set_transaction_timeout(Some(60000));
        let glue = Glue::new(storage);
        Arc::new(Mutex::new(glue))
    };
}
pub fn get_db_connect() -> Arc<Mutex<Glue<SledStorage>>> {
    SHARED_DB.clone()
}
pub fn execute_sql(sql: String) -> Result<Vec<Payload>,Error>{
    let glue_mutex = get_db_connect();
    let mut glue = glue_mutex.lock().unwrap();
    let output = glue.execute(sql);
    drop(glue);
    output
}
```
Test Code:

```rust
#[cfg(test)]
mod tests {
  use super::*;
  #[tokio::test]
  async fn create_table() -> std::io::Result<()> {
      let sql = "CREATE TABLE count(id INTEGER, rtype INT8);".to_string();
      let output = &execute_sql(sql).unwrap();
      println!("{:?}", output);
      let sql = "INSERT INTO count(id, rtype)values(1, 1), (1, 2), (1, 3), (1, 4), (1, 5);".to_string();
      let output = &execute_sql(sql).unwrap();
      println!("{:?}", output);
      let sql = "SELECT * FROM count;".to_string();
      let output = &execute_sql(sql).unwrap();
      println!("{:?}", output);
      Ok(())
  }
  #[tokio::test]
  async fn insert_table(){
      let sql = "SELECT * FROM count;".to_owned();
      let output = &execute_sql(sql);
      println!("{:?}", output);
  }
}
  ```
// create_table output everything is normal
![1684915801714](https://github.com/gluesql/gluesql/assets/129515418/a8951c24-5c9a-4f38-8f84-24a30ffa5319)

// then execute select_table, Output will be cant't found table count, mostly will be Ok([Select { labels: ["id", "rtype"], rows: []}]
//This is a probability event  i don't know why;
![1684916207253](https://github.com/gluesql/gluesql/assets/129515418/f1eeabaa-9248-4c3d-9135-67e8a8d8a8e0)

**Comment by enginefuture** [comment]
> The database connection code:
> 
> ```rust
> use gluesql::prelude::{Glue, SledStorage, Payload, Value as Gvalue};
> use anyhow::Result;
> use gluesql::core::result::Error;
> use std::{sync::{Arc, Mutex}, path::PathBuf, env};
> use lazy_static::lazy_static;
> 
> lazy_static! {
>     static ref SHARED_DB: Arc<Mutex<Glue<SledStorage>>> = {  
>         let mut storage = SledStorage::new(r"C:\Users\86136\data").unwrap();
>         storage.set_transaction_timeout(Some(60000));
>         let glue = Glue::new(storage);
>         Arc::new(Mutex::new(glue))
>     };
> }
> pub fn get_db_connect() -> Arc<Mutex<Glue<SledStorage>>> {
>     SHARED_DB.clone()
> }
> pub fn execute_sql(sql: String) -> Result<Vec<Payload>,Error>{
>     let glue_mutex = get_db_connect();
>     let mut glue = glue_mutex.lock().unwrap();
>     let output = glue.execute(sql);
>     drop(glue);
>     output
> }
> ```
> 
> Test Code:
> 
> ```rust
> #[cfg(test)]
> mod tests {
>   use super::*;
>   #[tokio::test]
>   async fn create_table() -> std::io::Result<()> {
>       let sql = "CREATE TABLE count(id INTEGER, rtype INT8);".to_string();
>       let output = &execute_sql(sql).unwrap();
>       println!("{:?}", output);
>       let sql = "INSERT INTO count(id, rtype)values(1, 1), (1, 2), (1, 3), (1, 4), (1, 5);".to_string();
>       let output = &execute_sql(sql).unwrap();
>       println!("{:?}", output);
>       let sql = "SELECT * FROM count;".to_string();
>       let output = &execute_sql(sql).unwrap();
>       println!("{:?}", output);
>       Ok(())
>   }
>   #[tokio::test]
>   async fn insert_table(){
>       let sql = "SELECT * FROM count;".to_owned();
>       let output = &execute_sql(sql);
>       println!("{:?}", output);
>   }
> }
> ```
> 
> // create_table output everything is normal ![1684915801714](https://user-images.githubusercontent.com/129515418/240531621-a8951c24-5c9a-4f38-8f84-24a30ffa5319.png)
> 
> // then execute select_table, Output will be cant't found table count, mostly will be Ok([Select { labels: ["id", "rtype"], rows: []}] //This is a probability event i don't know why; ![1684916207253](https://user-images.githubusercontent.com/129515418/240533555-f1eeabaa-9248-4c3d-9135-67e8a8d8a8e0.png)

Might be a multithreading issue.I have also met same problem before

**Comment by panarch** [comment]
Could you share the full response stdout result by `cargo test -- --nocapture`?
![image](https://github.com/gluesql/gluesql/assets/2025065/1983f41d-6953-4803-9cbb-e8641b783924)

If `insert_table` test runs eariler than `create_table`, it looks ok for tests to fail.
And... though you wrote `create_table` earlier than `insert_table`, it does not mean that `create_table` runs prior to `insert_table`.

**Comment by suncunxudsb** [comment]
I conducted the test separately,Execute create_table first, Wait a few seconds then execute insert_table

**Comment by panarch** [comment]
> I conducted the test separately,Execute create_table first, Wait a few seconds then execute insert_table

Ok, so you mean that you executed two commands separately.
does the below bash commands match the commands you tried?
```bash
cargo test -- --nocapture create_table
cargo test -- --nocapture insert_table
```

**Comment by suncunxudsb** [comment]
![1684994533343](https://github.com/gluesql/gluesql/assets/129515418/ff5a61bf-9c18-4b42-8706-55ff4830506a)
I clicked on these two buttons

**Comment by suncunxudsb** [comment]
Run create_table() two times in a row with a few seconds gap will fail. The error is table has exist! Indeed, the data was not saved for unknown reasons in the test case. And my colleague  did not occur this problem with main.rs.  This is indeed a common issue in my development environment. Then i will test the problem in the main.rs.
