### ISSUE TITLE
Using GlueSQL with Axum 

### ISSUE THREAD

**Issue by edezhic** [gluesql/gluesql#1245]
I'm trying to find a way to execute sql queries on `SharedMemoryStorage` inside [axum](https://github.com/tokio-rs/axum) handlers, but `.execute_async` future isn't `Send`, I suppose due to `[async_trait(?Send)]` but it's required by handler bounds, so it doesn't compile. At the same time, regular sync `.execute` function panics with `cannot execute 'LocalPool' executor from within another executor: EnterError`, which I suppose can be worked around using using tokio's `block_in_place` but might significantly hurt the performance. Any suggestions on how can I get around these problems? I really like the ideas behind GlueSQL but I'm having hard time figuring out how it is supposed to be used in multithreaded concurrent applications

**Comment by ever0de** [comment]
That's right. Since we are using `#[async_trait(?Send)]`, we are asking for `Pin<Box<dyn Future<..> + "Send">>` and not doing it.
I think we decided on this interface to support WebStorage in the past. 
- [Storage in web_sys does not implement Send](https://docs.rs/web-sys/latest/web_sys/struct.Storage.html#impl-Send-for-Storage)

I've tried a few things to work around this, but the current solution I can think of is to distinguish between traits that return Future, which always require Send, and traits that do not.

**Comment by edezhic** [comment]
@ever0de do I understand correctly that there is no pretty solution to this right now, but it's something that should be addressed in the future?

**Comment by ever0de** [comment]
@edezhic 
I'm one of the people who thinks this needs to be fixed. I'm thinking of solving it by separating traits, as I wrote above. 

Example. 
```rs
#[cfg(feature = "send")]
store_trait!(async_trait)
#[cfg(not(feature = "send")))]
store_trait!(async_trait(?Send))

// macro expand...
// #[async_trait]
// trait Store {}

// #[async_trait(?Send)]
// trait Store {}
```

If I come up with a better way to do it, I'll probably do something else. Any other ideas?

**Comment by edezhic** [comment]
@ever0de  Tbh no idea right now, but I want to point out that I'm considering using axum with webstorage as well (inside a service worker, you can find an example of such usage here - https://github.com/edezhic/pwrsapp). Basically running instances of GlueSQL on both server and client but with different storages. I wonder how that might work

**Comment by ever0de** [comment]
Yes, the server and client would have to use different storage.
`WebStorage`, like `Axum`, requires a `Send` condition in the handler, so you can't use it for the following reasons.
- The WebStorage we support is being used through `web_sys`, so it fulfills the `!Send` condition.

I'll try to implement the above [comment](https://github.com/gluesql/gluesql/issues/1245#issuecomment-1585564784) first, so why don't you use a storage that implements Send on the server?

**Comment by edezhic** [comment]
@ever0de I won't use webstorage on the server for sure, most likely it would be sharedmemory or maybe even paired with sled. But I wonder whether it would be possible to use Axum+Glue<WebStorage> at all. In theory it would be a single-threaded environment so `Send` should be safe to implement, but I'm probably missing smth. These things don't look conceptually incompatible, but type signatures are definitely problematic here

**Comment by edezhic** [comment]
Just to add a bit of context, I think if these problems will be resolved it would open amazing capabilities for fullstack rust apps which might reuse client/server code, eg it would be relatively trivial to implement data synchronization like in [meteor.js](https://www.meteor.com/) framework and others. With a service worker such app will also be able to support mobile platforms in almost-native cross-platform fashion. I think the potential of such a stack is even greater than Flutter and alike since it would be based on open web standards

**Comment by ever0de** [comment]
Migrate to the issue #1265
