### ISSUE TITLE
Replace `actions-rs/toolchain` with `dtolnay/rust-toolchain`.

### ISSUE THREAD

**Issue by ever0de** [gluesql/gluesql#1249]
The [acrtions-rs/toolchain](https://github.com/actions-rs/toolchain/issues/216) project is not currently maintained.
Consider changing it to [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain).

**Comment by jongwooo** [comment]
Can I work on this issue?

**Comment by ever0de** [comment]
> Can I work on this issue?

Sure
