### ISSUE TITLE
Add `Expr::Array` support for `LIST` data type

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#1294]
e.g.
```bash
gluesql> select ARRAY[1,2,3];
[error] translate: unsupported expr: ARRAY[1, 2, 3]

gluesql> select [1,2,3];
[error] translate: unsupported expr: [1, 2, 3]
```

`ARRAY[1,2,3]` or `[1,2,3]` like inputs are supported by sqlparser-rs but we don't.
we can provide this functionality by supporting `Expr::Array(Array)` in sqlparser-rs

ref.
https://github.com/sqlparser-rs/sqlparser-rs/blob/a50671d95d34688529fbc3d4452bec164ff21497/src/ast/mod.rs#L558

**Comment by ChobobDev** [comment]
I would be happy to have a go with the following issue!
