### ISSUE TITLE
Blob type support

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#130]
1. Add a new type `Blob` to `gluesql::data::Value`.
It may match to `Blob` in `sqlparser::ast::DataType` and `HexStringLiteral(String)` in `sqlparser::ast::Value`.

2. Expand `sqlparser::ast::Value` to store raw `bytes[]`.
Then someone who wants to build AST without sql string, they can use raw bytes without converting into string.

@KyGost

**Comment by KyGost** [comment]
Oh, I don't recall why I was tagged in this?

**Comment by panarch** [comment]
I barely remember. You were trying to insert blob, but there's no feature supported so you might use `sqlparser` directly? or used text.

**Comment by ever0de** [comment]
It seems that BYTEA, which has a different name but performs the same function, is implemented as <https://github.com/gluesql/gluesql/pull/586>.

How about closing issue?

**Comment by panarch** [comment]
resolved in #586
