### ISSUE TITLE
sample code of (1) Rust custom storage, (2) print out in JavaScript ?

### ISSUE THREAD

**Issue by zeroexcuses** [gluesql/gluesql#1304]
I have defined a Rust custom storage via:

```
pub struct State_Sql { ... }

pub type RowIter = Box<dyn Iterator<Item = gluesql::prelude::Result<(gluesql::prelude::Key, DataRow)>>>

impl AlterTable for State_Sql { }
impl Transaction for State_Sql { }
impl IndexMut for State_Sql { }
impl CustomFunction for State_Sql {}
impl CustomFunctionMut for State_Sql {}
impl Metadata for State_Sql {}
impl Index for State_Sql {}

#[async_trait::async_trait(?Send)]
impl Store for State_Sql { ... }

#[async_trait::async_trait(?Send)]
impl gluesql::core::store::StoreMut for State_Sql { ... }

```

I can execute against it via:

```
impl State_Sql {
    pub fn execute(&mut self, s: &str) {
        let statements = gluesql::core::parse_sql::parse(s).unwrap();
        for s in statements.iter() {
            let s = gluesql::prelude::translate(s).unwrap();
            let _ = gluesql::prelude::execute(self, &s);
        }
    }
}
```

My code is compiled to wasm32 and runs in the Chrome Brower.

Question: Is there sample code showing how to display the output in JavaScript? The end result of gluesql::prelude::execute is https://docs.rs/gluesql/latest/gluesql/prelude/enum.Payload.html

I am looking for some nice way to convert this from a Rust/wasm32 memory representation to something that JavaScript can read + print.

Thanks!

**Comment by panarch** [comment]
in the case of GlueSQL JavaScript package, we convert `Payload` enum into json object so JS users can easily manipulate it.

ref. https://github.com/gluesql/gluesql/blob/main/pkg/javascript/src/payload.rs

if you consider to use in your custom needs, then I think that it would be good to use that payload conversion script.
