### ISSUE TITLE
Float literals without fractional part (ex. 42.0, 0.00) are intepreted as integers

### ISSUE THREAD

**Issue by cake-monotone** [gluesql/gluesql#1309]
Currently, all float literals without fractional part are interpreted as integer, not floats.

More specifically, the following tests have passed:
```rs
    test!("SELECT 0.0", Ok(select_with_null!("0.0"; I64(0))));
    test!("SELECT 1.0", Ok(select_with_null!("1.0"; I64(1))));
    test!("SELECT 42.0", Ok(select_with_null!("42.0"; I64(42))));
    test!("SELECT 1.1", Ok(select_with_null!("1.1"; F64(1.1))));
```

The issue becomes more apprent when using the GCD(i64, i64) function, which further confirms that float literals are being treated as integers:

```sql
gluesql> SELECT gcd(1, 1);
| gcd(1, 1) |
|-----------|
| 1         |

gluesql> SELECT gcd(1.0, 1);
| gcd(1.0, 1) |
|-------------|
| 1           |

gluesql> SELECT gcd(1.0, 1.1);
[error] evaluate: function requires integer value: GCD
```

**Comment by panarch** [comment]
ref.
https://github.com/gluesql/gluesql/blob/f5ffae1df5e8308f7cd67e68088daec5fef94d0b/core/src/data/value/literal.rs#L21-L37

in here,
```rust
            Literal::Number(v) => v
                .to_i64()
                .map(Value::I64)
                .or_else(|| v.to_f64().map(Value::F64))
                .ok_or_else(|| ValueError::FailedToParseNumber.into()),
```
we need to fix this, rather than calling `to_i64()` directly, checking fraction part needs to be done prior to integer conversion.

**Comment by panarch** [comment]
ref. https://docs.rs/bigdecimal/latest/bigdecimal/struct.BigDecimal.html#method.is_integer
It looks that we can use `BigDecimal::is_integer` method

**Comment by panarch** [comment]
ref.
```rust
Literal::Number(v) if v.is_integer() => v
    .to_i64()
    .map(Value::I64)
    .ok_or_else(|| ValueError::FailedToParseNumber.into()),
Literal::Number(v) => v
    .to_f64()
    .map(Value::F64)
    .ok_or_else(|| ValueError::FailedToParseNumber.into()),
```

**Comment by ZuoTiJia** [comment]
Maybe a new type should be added here, such as Interger (Bigint).
https://github.com/gluesql/gluesql/blob/2c10ac20c56dc5e008720aa11e31fc9073ec3d31/core/src/data/literal.rs#L59-L65
