### ISSUE TITLE
Is it possible to query another database rather than the default one?

### ISSUE THREAD

**Issue by sanchezcarlosjr** [gluesql/gluesql#1318]
In my application, I have multiple IndexedDB databases, so a interesting feature is the ability to switch my database.

I attempted to write

```sql
USE "rxdb-dexie-eva_notebook--0--blocks";
```
but it didn't work.

![image](https://github.com/gluesql/gluesql/assets/24639141/0bade113-cdeb-4f67-b051-4e316babe567)

**Comment by panarch** [comment]
IndexedDB storage itself has namespace feature but.. for now JS package does not support it.
I think that the custom namespace functionality can fit your needs, would it be right approach?

Then, I consider to add namespace parameter for `loadIndexedDB` function.

**Comment by sanchezcarlosjr** [comment]
It works for me. Thank you!

**Comment by panarch** [comment]
> It works for me. Thank you!

Ok that's simple task so I'll let you know after the work

**Comment by sanchezcarlosjr** [comment]
I've managed to integrate GlueSQL with my open-source computational notebook. [This](https://notebook.sanchezcarlosjr.com/?t=lyuklmrajm&p=hooofiqdrk&c=Gw0mAJyHsbG0%2BNBsXurEV42bEZLM%2BqHTd1ovl1IfljACUmrnF4EwyEUiIJc2bEsKcDJ1WLqCy4%2FW%2BP2EhEalVY%2BVm9k398UlYT47s3uIWfsVsUgSj4lKjeIhkggZtw38IIg%2FQv0xXF38vtJAQESs7atrz%2BGfyTiO4iwSHMP64IH93bM1jM3q86%2BJ%2FPJnWXLMq4InEAVDoGrq9xv5hN9AMP%2BuMbd4%2FYI%2BfPz2%2F5C59Qvv6Zo1%2FzCvjdf%2FuTI77hNRW9bm2ZO77rdNTAGbP8ZqvP7vj9l3Lb9%2B8fssrr%2Fxi06lu%2Bm7fIvp2Yjx8G9OhgwqqIl7bgbd13%2FmGr43glGv1V2HKkvuc8HkGrCiqFapaiRSxYqJfXkthSj4QTkkYGCg%2ByAx%2B10D8Ts85nMQlPGFDsiLBmREFVeKeMnCVJEJK0L8aYIbUKVIKFw98qoeflwTGMkfBLGoR%2Fkyg5BwHgyp4U10hkvdIhcAYOmHxp3kDqBhBxteMTVWLMaQk%2FHha7RZ%2BptQymKw9mu5eAuY50G%2FZF5vgGqa5dN8WLe3bmI3rtSLHxSYb8LRUgasa3wNcWCgCNKC2EeAVw4PrkzWoBkAzEEUTOBgkCF2fzLdWw2%2FdoMvpJsBVCHYBifCjsl67o0gCVtFSyfwnHHISJR4xEGDixbr4t3N801E760ub6AO2jbnGRGghS0h7jw7Q%2FSSysxEmyoNemhCNSgZ43N9wbqVngfgWka8RLfLZoo2PnUWfUWSRtXCXfS26%2Bb1Pfk3Yovpty7TgKmPN8HCl1XU4JBVUKJjW5QKwwsYau0G2CR%2B6cxLaqS1LhWzwKCG1V8ehCpUxgBsks3pToPs%2Fy5CIyTvjtCfdIdW5T2Qv6%2BJy9fvIsyVe3wjTPZZfZiRVud0MosLWYZODUQ%2BnBWl6dSPXY4BKtcsyKESTqjZAhj6im1qduo4O3vlgsPXhYKp91DYiZMnI0d8Bnq%2FNnH44Rh6pHQ8YIgWbUH6aOowNq7KmxFWTn6JOA%2BhRS9YbwGggSdZ0mFD3oivg71%2Bk2IUQfLJEX95EjcRvIlsjCxAwHIA1oAvXWzKD6WsLvQ722q29WiEtcp6dxrBd5oOUkk2vy5lhan%2BTt%2BjNG2npRB3TYUUXrSg9Uu%2BwWqQdc2n%2Bp5SQSHeY397uc2cU8zMtQmmNLJz%2BeM%2BiTjNsP2tHwjRQQ8pFvhexCL%2Fg%2BWfRQzkyEJ74QG9NqQDMiB06l5KbW0n%2FjI0GKWRrPUSNF1brKKFNGJmHt12CPWCrkyaUrLRJ1JHyCNhheg2WWijj5Db1XkoICz2K57w0tf7kFteQ6JM3dyBC7mYcNsub0Pg%2FKfqL%2BiScnMzudo6KbSuJ4f%2Ba0qi6cFBLh21X2JkajUUlOorhrQawa8KUAckKv9jNBUl9Lv76OtsUdZ4qUoxK5IpOqmOunyfEkwG%2FECEbXGjWHrS2%2B%2BFnmKvTpEK0ZzPgrlppul58F2t7Vq3JxWcOidLn1OY0HMSBhvPR%2FCFQRBV4w%2BFEMbAadEX9Xh7iJWpwa5JDHQz%2FDKYzLmRqgpOmNaj89rO0KriB%2FJ1x0liQO6k4t1qUoufgjTeMZXNXtnkftdkhDDGoi5rrBAl9QnjDZ9Fz%2BuqFZA4vPHsdp77B6IHdbmyO6S2dD5UbW1S9jqlEEZQi9H3LgpVm3N%2BFHEEesnJd52dDduITZsbix21bsGgOOmSlO7kasDzCKXGCJ8d%2BC7qgxWCWnLLfoptFqUv%2FUYdRYNMaLOL90CrhxGwAjScFSLSKAOmTsiwWNk68y1hs6DdEmdIMbazO1aUTfNWvCKmAeNh1wZJCkT0TBn7sKIFj9TCKNwx1r218JOBuiVpnb7Iv24zG%2BNoxHBjMrOkuRczLUXLxmyJI%2BHi8U5LCA22poNlNRLD9nIsA9bAwrr%2B57znJjV2bhYq8fCLmJ0kd4VAe%2BazMY5sR%2BofVs16rI4nXmhqqbfFSbQUu6br4P30HVTsFq50o34qFhR9I6mbCdEcEcqwnd5nJMVcUb9aqF2s%2BtFWjFc9rJoWuhIAV8d8Vj3961f9KdVpnanUzMmyrnimQROmKUDOoUPb7YpkOZw4RDAdjtgIn0qS%2FkuK%2FISkIIRkOgtdFmzlHdyg08hWKntDvUQxqabMRQcZNeehBfNnKJQkJ8m77u1L94NTIxD8F0Wph9r2lgUedFcYtFKniRhpeg1g1VwWjKqZiHaenfl1FazEUrVJurqw2cQpGYpjY6miRFI27PlOJpTOkdJ9naQ7IP2eUET5mGS8UyA%2BqWYne0kJohRWfxSyRbPE4pn5nM5gnrfTiNkvOlrj6PUzE8Z%2Fz9WbIIi09uev2ulG5HYTlL7LI3Vb7J5PchzJjGQ8RxKpnBKxwP89yXyeIt187Rx%2FFtuipQ8mHqnIMqdp4QEfb%2FHxIKeIY9O1PuLX89eLx6Z9%2BeHViaYWyje2oOdsrQz1JtTyamBTdsMZl8eP)  could serve as an example.

It could potentially be a playground for GlueSQL users.

![image](https://github.com/gluesql/gluesql/assets/24639141/9be6ef43-652f-48c0-8572-6860ced8795d)

**Comment by panarch** [comment]
@sanchezcarlosjr 
```
npm i gluesql@0.14.4-rc.1
```

can you try `0.14.4-rc.1` version? then you can use namspace when you call `loadIndexedDB`.
because it may take some time to release 0.15 so I've released with rc tag.

**Comment by sanchezcarlosjr** [comment]
It works. Thank you. I'm closing the issue.
