### ISSUE TITLE
Remove `From<Value> for Evaluated<'a>`

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#1328]
https://github.com/gluesql/gluesql/blob/5d96a9aca9fdbd4bd457a7831db708fe29402c0c/core/src/executor/evaluate/evaluated.rs#L21-L25

This `From` impl only shorten 
```rust
Evaluated::Value(value)
```
to
```rust
Evaluate::from(value)
```

Now there's no reason to keep using this code. we can simply use `Evaluated::Value` instead.
Let's remove this.
Once we remove the declaration codes and run `cargo check`, then `cargo` will lead us what to do.

**Comment by tgsong827** [comment]
Could you please assign this issue to me?
