### ISSUE TITLE
Implement ast_builder for bitwise_not operator

### ISSUE THREAD

**Issue by gurugio** [gluesql/gluesql#1350]
Implement ast_builder for bitwise_not operator

**Comment by panarch** [comment]
resolved in https://github.com/gluesql/gluesql/pull/1321

**Comment by gurugio** [comment]
@panarch Hi, this issue is not completed yet.
I didn't start.
Could you please open this ticket again?

**Comment by panarch** [comment]
Oh thanks! I thought that #1321 is a related issue but it was not

**Comment by gurugio** [comment]
https://github.com/gluesql/gluesql/pull/1366
