### ISSUE TITLE
How to init IdbStorage with Rust?

### ISSUE THREAD

**Issue by gitmalong** [gluesql/gluesql#1377]
I have a hard time finding the info how to init a certain storage. By digging into the source code I found:

```rust
let storage = IdbStorage::new(Some(namespace.to_owned())).await.unwrap();
let mut glue = Glue::new(storage);
```

but this does not work for me

Dependencies
```rust
gluesql-core = "0.14.0"
gluesql-idb-storage = "0.14.0"
```

Import
`use gluesql_idb_storage::IdbStorage`
-->
```rust
unresolved import `gluesql_idb_storage::IdbStorage`
no `IdbStorage` in the root
```

Starter project I am using: https://github.com/leptos-rs/leptos/tree/main/examples/tailwind_csr_trunk/src

**Comment by gitmalong** [comment]
I had to add

```toml
[build]
target = "wasm32-unknown-unknown"
```

to `.cargo/config`

**Comment by ever0de** [comment]
Yes that's right, idb-storage only has code for wasm32.
See the following

https://github.com/gluesql/gluesql/blob/ce5e930a63f90d55f6744a28b7a91ffbdc5e1e61/storages/idb-storage/src/lib.rs#L1
