### ISSUE TITLE
doc: How to map Payload back to struct?

### ISSUE THREAD

**Issue by gitmalong** [gluesql/gluesql#1378]
Hi!

What is the proper way to go from select() ->`Payload` to a custom struct?

I could not find any examples regarding that and the doc does also not mention it.

Thanks

**Comment by gitmalong** [comment]
I found that this works but I am not sure if this is the best way to do so.

```rust
    let selected = table("settings")
        .select()
        .filter("year = 2023")
        .execute(&mut glue)
        .await
        .unwrap();
        
        match selected {
            gluesql_core::prelude::Payload::Select { labels, rows } => {
                let time_zone_i = labels.iter().position(|x| x == "time_zone").unwrap();
                let currency = labels.iter().position(|x| x == "currency").unwrap();
                Settings {
                    currency: rows[0][currency].clone().into(),
                    time_zone: rows[0][time_zone_i].clone().into(),
                } 
            },
            _ => panic!(),
        }
```

**Comment by ever0de** [comment]
Try using `Payload::Select` if you have a schema, or `Payload::SelectMap` if you don't, to fetch rows.

My recommendation is to create a struct and implement `TryFrom` for `Payload` and struct
e.g) <https://github.com/ever0de/gluesql/commit/a0ccda265b76fca305bd72a18316723f985e83ef#diff-6ecd13eab89cbf9d6f327f55c2a4a177059a5407406d3560a1bf07862a2b36fdR11>

**Comment by gitmalong** [comment]
Thanks! How can I provoke getting a SelectMap from my select query builder?

**Comment by ever0de** [comment]
The return values of the `AstBuilder::execute` and `Glue::execute` functions are similar.

- https://docs.rs/gluesql/latest/gluesql/core/ast_builder/trait.Execute.html
- https://docs.rs/gluesql/latest/gluesql/prelude/struct.Glue.html#method.execute

You can remove `Vec::remove` from the above example, because you get `Payload` instead of `Vec<Payload>`.

**Comment by gitmalong** [comment]
Thanks for the hints. A macro like https://docs.rs/sqlx/latest/sqlx/trait.FromRow.html would be useful to derive `impl TryFrom<Payload> for MyTable`.
