### ISSUE TITLE
AUTOINCREMENT does not work?

### ISSUE THREAD

**Issue by pengyizeng** [gluesql/gluesql#1381]
I create a simple table : user
eg:
        let sql = "
            CREATE TABLE user (
                 id INTEGER PRIMARY KEY AUTOINCREMENT,               
                 name TEXT
           );";

 created successfully. Then I insert a record without specify the id number:

        let sql2 =  "INSERT INTO user(name) VALUES ('John'); ";
 
It occurs an error which tells me I did not specify the "id", how can I insert data without specify the "id"?

**Comment by ever0de** [comment]
ref: https://github.com/gluesql/gluesql/issues/159

**Comment by pengyizeng** [comment]
> This feature is not currently supported.
> 
> ref: #159

Thanks, then I use UUID as the "id" type, and insert data successfully by "generate_uuid()" . But when I select  the data by an id:
eg:
 ```
  let uuid = "48743284824.....";
  let actual = table("user")
    .select()
    .filter(col("id").eq(uuid))
    .project("id, name")
    .build()
    .expect("build and execute")
    .execute(glue)
    .await;
```
  went wrong, how to specify the filter when the id type is UUID?

**Comment by ever0de** [comment]
https://github.com/gluesql/gluesql/blob/ecc6fdf7ee72cc51dec0a6c7fe51e7ff0d6c6926/test-suite/src/data_type/uuid.rs#L44-L74

https://github.com/gluesql/gluesql/blob/ecc6fdf7ee72cc51dec0a6c7fe51e7ff0d6c6926/core/src/data/value/literal.rs#L121
https://github.com/gluesql/gluesql/blob/ecc6fdf7ee72cc51dec0a6c7fe51e7ff0d6c6926/core/src/data/value/literal.rs#L620-L624

Can you provide a little more information?

If I add the test case below, it works fine.
```rust
    let actual = table("Foo")
        .create_table()
        .add_column("id UUID")
        .add_column("name TEXT")
        .execute(glue)
        .await;
    let expected = Ok(Payload::Create);
    assert_eq!(actual, expected, "create table");

    let actual = table("Foo")
        .insert()
        .columns("id, name")
        .values(vec![vec![
            text("936DA01F9ABD4d9d80C702AF85C822A8"),
            text("hi"),
        ]])
        .execute(glue)
        .await;
    let expected = Ok(Payload::Insert(1));
    assert_eq!(actual, expected, "insert");

    let actual = table("Foo")
        .select()
        .filter(col("id").eq(text("936DA01F9ABD4d9d80C702AF85C822A8")))
        .project("id, name")
        .execute(glue)
        .await;

    let uuid = Uuid::parse_str("936DA01F9ABD4d9d80C702AF85C822A8")
        .unwrap()
        .as_u128();
    let expected = Ok(select!(
        id     | name
        Uuid   | Str;
        uuid   "hi".to_owned()
    ));
    assert_eq!(actual, expected);
```

**Comment by pengyizeng** [comment]
I think I should use parse_uuid() instead of using the u128 string format, thanks a lot!
