### ISSUE TITLE
Make `impossible cast` error more meaningful

### ISSUE THREAD

**Issue by gitmalong** [gluesql/gluesql#1390]
During an AST constructed select I am getting `value: impossible cast` without any further hints which makes it hard to debug.

```rust
let payload = table(TABLE_NAME)
    .select()
    .filter(format!("year = {year}"))
    .execute(glue)
    .await;
```

**Comment by ever0de** [comment]
https://github.com/gluesql/gluesql/blob/ff75442d85f4025c0aaba9800d90308bc8b52230/core/src/data/value/error.rs#L101

We need to add a field for the `ImpossibleCast` variant.
1. A `Value` or the current `DataType`.
2. the `DataType` you want to convert to
3. (TODO Optional) It would also be nice to know the name of the selected column or ast... etc, but that seems hard to get from an implementation like `Value::TryFrom`.
