### ISSUE TITLE
CASE expression support

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#140]
https://www.sqlitetutorial.net/sqlite-case/

```sql
CASE case_expression
     WHEN when_expression_1 THEN result_1
     WHEN when_expression_2 THEN result_2
     ...
     [ ELSE result_else ] 
END
```

This is for evaluating `sqlparser::ast::Expr::Case`

**Comment by KyGost** [comment]
Working on this

**Comment by KyGost** [comment]
I take it back, maybe at some other time hahaha

**Comment by KyGost** [comment]
@MRGRAVITY817 
If desired I have a working solution in https://github.com/SyRis-Consulting/multisql

**Comment by panarch** [comment]
https://github.com/SyRis-Consulting/multisql/blob/0d4b7953add8509fae11dc259deca88e0ae23e27/src/executor/recipe/resolve.rs#L126-L148

@KyGost Sounds good to look around :)

Current status in this PR is also working well, we are now trying to make the code quality better and easier to read.
@MRGRAVITY817 has successfully removed `unwrap()` uses, and the only remaining stuff is eliminating `clone()`.
It would be also nice that you can also participate by sharing ideas here.
