### ISSUE TITLE
Composite Storage support CTAS

### ISSUE THREAD

**Issue by enginefuture** [gluesql/gluesql#1432]
I have a table stored in Sled. Due to the large amount of data, the join query speed is very slow. I want to copy this table into memory, using Composite Storage for querying. I attempted to create it using the following SQL statement:
 ```rust
            let memory_storage = MemoryStorage::default();
            let mut storage = CompositeStorage::new();
            let Glue {
                storage: sled_storage,
            } = &*db.lock();
            storage.push("MEM", memory_storage);
            storage.push("SLED", sled_storage.clone());
            storage.set_default("SLED");
            let mut glue = Glue::new(storage);
            let start_time = Instant::now();
            let res = &glue
                .execute("CREATE TABLE MEM_material ENGINE = MEM AS (SELECT * FROM material);")
                .unwrap();
```
```sql
CREATE TABLE MEM_material ENGINE = MEM AS (SELECT * FROM material);
```
However, a syntax error occurred. Is there a problem with my usage, or does Composite Storage not currently support this syntax?

**Comment by suncunxudsb** [comment]
Yes, I also encountered this problem. Have you solved it

**Comment by enginefuture** [comment]
noup

**Comment by wawnchg** [comment]
I have the same problem, is there any good solution?

**Comment by devgony** [comment]
Currently, CTAS does not work with ENGINE option but only works with default storage.
So, you could do like this.
```rs
glue.execute("CREATE TABLE material (id INT, name TEXT) ENGINE = SLED;");
glue.set_default("MEMORY");
glue.execute("CREATE TABLE MEM_material AS SELECT * FROM material;");
```

By the way, Can you share below information? It might help a lot to improve query performance.
- The slow query
- The row number of each tables in the slow query
- Schema of each tables
- PK on each tables
- Indexes on each tables
