### ISSUE TITLE
Missing impl From<Uuid> for ExprNode

### ISSUE THREAD

**Issue by edezhic** [gluesql/gluesql#1448]

**Comment by panarch** [comment]
e.g.
https://github.com/gluesql/gluesql/blob/235fd6e4cf8145dfb232f9618ba4954cce32fe45/core/src/ast_builder/expr/mod.rs#L304-L308

**Comment by panarch** [comment]
`CAST("somethinguuidstring" AS UUID)` impl would be prior task to implement

**Comment by panarch** [comment]
for now, you can use cast function to convert literal text into uuid.
