### ISSUE TITLE
Multiple Filters

### ISSUE THREAD

**Issue by kanekoshoyu** [gluesql/gluesql#1451]
Hi,

I was wondering if there is any plan or a current workaround for using multiple filters (esp on select and update)

Originally I had a misunderstanding on AST builder syntax and I thought adding .filter() multiple times will keep adding nested filter, but turns out every new filter was just overriding another filter.

Then I tried adding AND within one filter expression, but I do not see the effect of the nested filter. From what I tested, it seems like only the first condition in the filter gets recognized, and the rest is discarded.

I saw online that we might be able to use subqueries (queries on top of queries) to get it solved. I am wondering if there is anything similar to such a concept in gluesql that I can use as a workaround.

Example of AND/OR within WHERE
https://www.techonthenet.com/sql/where.php

**Comment by devgony** [comment]
To use AND or OR expression, you should do like this.

```rust
        .filter(
            col("name")
                .not_like(text("D%"))
                .and(col("name").not_like(text("M___"))),
        )
```
https://github.com/gluesql/gluesql/blob/main/test-suite/src/ast_builder/expr/pattern_matching.rs#L69
or
```rust
        .filter("c.name = 'Fruit' OR c.name = 'Meat'")
```
https://github.com/gluesql/gluesql/blob/main/test-suite/src/ast_builder/select.rs#L85

**Comment by panarch** [comment]
> Originally I had a misunderstanding on AST builder syntax and I thought adding .filter() multiple times will keep adding nested filter, but turns out every new filter was just overriding another filter.

adding filter multiple times should work like below,
if it wasn't then could you provide the query you tested?

https://github.com/gluesql/gluesql/blob/235fd6e4cf8145dfb232f9618ba4954cce32fe45/core/src/ast_builder/select/filter.rs#L142-L150

**Comment by kanekoshoyu** [comment]
> To use AND or OR expression, you should do like this.
> 
> ```rust
>         .filter(
>             col("name")
>                 .not_like(text("D%"))
>                 .and(col("name").not_like(text("M___"))),
>         )
> ```
> 
> https://github.com/gluesql/gluesql/blob/main/test-suite/src/ast_builder/expr/pattern_matching.rs#L69 or
> 
> ```rust
>         .filter("c.name = 'Fruit' OR c.name = 'Meat'")
> ```
> 
> https://github.com/gluesql/gluesql/blob/main/test-suite/src/ast_builder/select.rs#L85

Sure, this worked fine for select(). for update() I tried the other day and was not working.

**Comment by panarch** [comment]
> Sure, this worked fine for select(). for update() I tried the other day and was not working.

thanks, yes it was only working for select().
I just add concat filter support to ast builder update nodes.
this will be included in the next release.

ref.
[Update AST builder UpdateFilterNode .filter(..) behavior, #1455](https://github.com/gluesql/gluesql/pull/1455)
[Update AST builder UpdateNode to enforce .filter(..) before .set(..), #1454](https://github.com/gluesql/gluesql/pull/1454)
