### ISSUE TITLE
Non-string API

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#148]
It would be nice to add a non-string api, that is to say a way to (mostly just) `INSERT` data and provide a `vec` rather than having to concatenate or work around GlueSQL.

Would this be best as a seperate repo, an optional component just a regular component?

**Comment by panarch** [comment]
This sounds interesting to have, but not sure what would be a good way to add this feature.
If that is for supporting full sql functionality, then we can consider this as an.. ORM and it's better to use a seperate repo.
However, current main needs looks limited to inserting data.
Then optional component approach might work well.

**Comment by KyGost** [comment]
I think API should work like:
`insert_vec(table_name: String, columns: Vec<String>, rows: Vec<Vec<Value>>)`

Maybe even also:
`insert_string_vec(table_name: String, columns: Vec<String>, rows: Vec<Vec<String>>)`
