### ISSUE TITLE
String only output API

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#149]
In the same vein as #148, it'd be nice to have some API.
Same questions re method of implementation.

It would be good if there was a API side way of getting results as `Vec<Vec<String>>` instead of `Vec<Vec<Value>>`.

**Comment by panarch** [comment]
Sounds good :) Thanks for the suggestion.
This one, we can easily support it by [trait.ToString](https://doc.rust-lang.org/std/string/trait.ToString.html) for `gluesql::data::Value`.

Implementing `ToString` trait and adding some unit tests to `Value` would be enough.

**Comment by KyGost** [comment]
Same thing with JSON output too

**Comment by panarch** [comment]
@KyGost JSON output sounds also good, in this case, it would be good to customize `serde` serialize, https://serde.rs/impl-serialize.html

**Comment by KyGost** [comment]
@panarch gave a useful link for this: https://github.com/gluesql/gluesql-js/blob/main/src/convert.rs

**Comment by KyGost** [comment]
I think that JSON should be represented as:
For:
`SELECT name, fruit_id, rating FROM favourite_fruits`
Get:
```JSON
[
  {"name": "John", "fruit_id": 7, "rating": 9.3},
  {"name": "Bob", "fruit_id": 2, "rating": 1.0}
]
```

**Comment by KyGost** [comment]
TODO:
- [x] `parse_single`
- [x] `select_as_string`
- [ ] `select_as_json`
- [ ] `insert_vec` resolve #148
- [ ] `insert_csv` resolve #153 (alternative to)
