### ISSUE TITLE
Public all `ast_builder` Type

### ISSUE THREAD

**Issue by xhanl** [gluesql/gluesql#1547]
# Description
I'm creating a simple ORM for gluesql based on derive, it will auto impl some gluesql methods for struct, like:
```rs
#[derive(GlueSqlModel)]
pub struct File {
    #[gluesql("PRIMARY KEY")] pub id: u64,
    #[gluesql("NOT NULL")] pub name: String,
    #[gluesql("NOT NULL")] pub size: u64,
    #[gluesql("NOT NULL")] pub created_at: NaiveDateTime,
    #[gluesql("NOT NULL")] pub modified_at: NaiveDateTime,
}
```
will generate 
```rs
impl File {
    pub fn from_gluesql_row(row: Vec<gluesql::core::data::Value>) -> Self {
        Self {
            #(#field_assignments),*
        }
    }

    pub fn to_gluesql_row(&self) -> String {
        vec![#(#field_values),*].join(",")
    }

    pub fn create_gluesql_table() -> gluesql::core::ast_builder::CreateTableNode {
        gluesql::core::ast_builder::table(#table_name)
            .create_table()
            #(#add_column)*
    }

    pub fn drop_gluesql_table() -> gluesql::core::ast_builder::DropTableNode {
        gluesql::core::ast_builder::table(#table_name)
            .drop_table()
    }

    // ...
}
```

For flexibility, I decided to use `ast_builder` nodes as the function return type, so user can custom them as they want.

But some `ast_builder` type like `TableNameNode` or `InsertSourceNode` are not public, so the following functions cannot be implemented:
```rs
    pub fn gluesql_table() -> gluesql::core::ast_builder::TableNameNode {
        gluesql::core::ast_builder::table(#table_name)
    }

    pub fn insert_to_gluesql_table() -> gluesql::core::ast_builder::InsertSourceNode {
        gluesql::core::ast_builder::table(#table_name)
            .insert()
            .values(vec![#(#field_values),*].join(","))
    }
```
- Is it possible to expose all the node types of ast_builder?
- If you are interested in the details of this ORM, or have a better idea, we can discuss, too

**Comment by panarch** [comment]
> Is it possible to expose all the node types of ast_builder?

All the ast_builder Nodes are supposed to be public, if some are not, then we can expose it easily.
you can see the codes here
ref. https://github.com/gluesql/gluesql/blob/a29114262c03be0d53ec1a9e61138b90a774a35a/core/src/ast_builder/mod.rs#L42-L74

any kind of pub but not exposed ones, could you make the pull request for those? I can merge that right after.

> If you are interested in the details of this ORM, or have a better idea, we can discuss, too

yeah, current the ast builder has only the role of query builder.
it would be really nice to support ORM if we can.
here ORM can take two roles
- schema validation
- deserialization of the query result

https://github.com/gluesql/gluesql/blob/a29114262c03be0d53ec1a9e61138b90a774a35a/core/src/ast_builder/execute.rs#L13-L23

I think.. that how about making the alternative of this `Execute` trait?
you can make your own `Execute` trait which takes the ORM schema struct.
then, that custom `Execute` trait can validate the schema and deserialize the payload to the ORM struct.
it is simple to make the custom `Execute`

e.g.
https://github.com/gluesql/glues/blob/adb0e6f78b22e7c3ce0394b2064f8b635e84de95/core/src/db.rs#L60-L84
https://github.com/gluesql/glues/blob/adb0e6f78b22e7c3ce0394b2064f8b635e84de95/core/src/db/note.rs#L64
