### ISSUE TITLE
gluesql_core::ast::data_type::DataType is missing Int64

### ISSUE THREAD

**Issue by barsdeveloper** [gluesql/gluesql#1587]

**Comment by devgony** [comment]
You can consider DataType::Int as Int64

https://github.com/gluesql/gluesql/blob/main/core/src/translate/data_type.rs#L13-L15

```rust
        SqlDataType::Int(None) | SqlDataType::Integer(None) | SqlDataType::Int64 => {
            Ok(DataType::Int)
        }
```

**Comment by barsdeveloper** [comment]
I see, thanks, it was not clear considering there is Uint64, I think, for symmetry Uint64 should be Uint, great project anyway. Thanks
