### ISSUE TITLE
Refactoring crate::data::Value and removing Value::Empty

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#166]
Thanks to @KyGost 👍 

Prior threads,
- https://github.com/gluesql/gluesql/pull/163
- https://discord.com/channels/780298017940176946/780298017940176949/818732114782060555

Goals,
1. Removing `Value::Empty` and replace it to use `Opt-` prefixed values.
`Value::Empty` was for representing `NULL` values which is filter out by outer join condition failures.
However, it looks not worth enough to distinguish between normal `NULL`s and join failure `NULL`s.
After we replace `Value::Empty` to `Value::Opt-` based one, then we can also remove
![image](https://user-images.githubusercontent.com/2025065/110453253-51ae5380-8109-11eb-8374-2a1c21b89ec2.png)
`select_with_empty!` test helper macro.
What it means is that each column per row can really have a same type.

2. Refactoring `Value`
Current implementation of `Value` handles nullable types and non-nullable types in a same depth.
This causes internal `Value` methods to quite hard to read and write codes.
Current:
```rust
pub enum Value {           
    Bool(bool),            
    I64(i64),              
    F64(f64),              
    Str(String),           
    OptBool(Option<bool>), 
    OptI64(Option<i64>),   
    OptF64(Option<f64>),   
    OptStr(Option<String>),
    Empty,  // will be removed first                
}                          
```
Planning to do: (enum names might be changed)
```rust

enum Value {
    NotNullable(InnerValue),
    Nullable(Option<InnerValue>),
}

enum InnerValue {
    Bool(bool),
    I64(i64),
    F64(f64),
    Str(String),
}
```

**Comment by panarch** [comment]
@KyGost type alias sounds nice, we might use well.
However,
```rust
type Value = Option<InnerValue>
```
This looks different because `Value`
```rust
enum Value {
    NotNullable(InnerValue),
    Nullable(Option<InnerValue>),
}
```
here `Value` needs to have both `Optional` and Non-nullable. but using `Option<InnerValue>` it can only represent nullable value.

**Comment by KyGost** [comment]
Why do we want `NonNullable`?

**Comment by panarch** [comment]
@KyGost 
Because if we don't use `NotNullable` then every column will become optional.
This is a simple translation from the current 1-step `Value` to 2-step `Value-InnerValue` codes.

First intention I decided to keep non-opt and `Opt-` values in 1-step `Value`, it was because I also worried about the case which it would cause more code, processing.
However, this 2-step nesting can make `Value` codes much more readable than now.

**Comment by panarch** [comment]
@KyGost Ok two points.

For this kind of purpose, we cannot use type alias like this, `type Value = Option<InnerValue>`.
Because we cannot `impl` on type alias.
So, we still need to use some kind of `enum` to represent `Option<InnerValue>`, 2-step.

The other point is...
If we simply use only `Option<Value>`, then every column becomes nullable.
Once we use 2-step enums, supporting both `NotNullable` and `Nullable` does not require much extra cost but it can provide a meaningful function, delivering `NotNullable` info to end-user.

**Comment by panarch** [comment]
@KyGost btw, it might be little bit different topic, though we use 2-step value, we can only use 2-step value for internal implementation. Then, for end-user, by something like `flatten` work, it is possible to keep current `Value` enum structure.
```rust
pub enum Value {           
    Bool(bool),            
    I64(i64),              
    F64(f64),              
    Str(String),           
    OptBool(Option<bool>), 
    OptI64(Option<i64>),   
    OptF64(Option<f64>),   
    OptStr(Option<String>),
```

nested value to end-user might be a bit bothersome stuff so.. this kind option is also considerable.

In anyway, I'll firstly focus on removing `Value::Empty` for now.

**Comment by panarch** [comment]
@KyGost Oh, that `struct Value(Option<..>)` really makes sense, I didn't aware of that, thanks :)
I'll just spend a single more day to think about this whether `NotNullable` is really meaningful info to keep.

For now, something makes me hesitate to decide this kind of reducing information, but nothing is certain for now.

How about this?
Row stores `Vec<Value>` and now it is obvious for `NOT NULL` columns because `NULL` cannot be stored.
However if we change to `Vec<Value(Option<InnerValue>)>`, then storage needs to storage nullable value though it is not null.
Then every time we scan_data on storage values, we need to do null checks to verify it's data fits to the schema column def.

**Comment by KyGost** [comment]
@panarch 
Aren't we doing that anyway?

Also, we could keep them blank and assume `None` by default, easier than assuming something like `OptStr(None)`? :-)

Sleeping on it sounds good.
I'll be off for the night very soon but would be happy to talk more about it tomorrow.

**Comment by panarch** [comment]
Ok, let's keep talk about this tomorrow, thanks :)

**Comment by panarch** [comment]
I think two independent topics were mixed but we handled together yesterday.

1. For end-users, is providing more info of `NULL` meaningful?
Here, you mentioned it is not necessary, and I also... have no proper reason about why it is really necessary for users.
Someone who just wants to use sql db casually, they would be simply ok with this kind of values,
```rust
enum Value {
    Bool(bool),
    I64(i64),
    F64(f64),
    Str(String),
    Null,
}
```
Because above is what other sql databases are doing.

2. For internal code quality, is it ok to convert all non nullable values to nullable?
Here would be the topic we have different opinions.
In the current codes, we know whether values are nullable or not.
If we convert all values to `Option`, it means every value can become null, no matter it is really possible or not.

```sql
CREATE TABLE Foo (
  id INTEGER NOT NULL,
  id2 INTEGER NULL,
);
```
In this example, we are able to use not nullable type `I64` to `id INTEGER NOT NULL` and nullable type `OptI64` to `id2 INTEGER NULL`.
However, after we all use only nullable value, it becomes not possible.
Is this right that your intention is putting `Option<Value>` to `NOT NULL` type?

**Comment by KyGost** [comment]
1
---
You're right, that option of the 4 types + Null is pretty good.
Hmm this does raise the question, perhaps that would be good; would it be nicer to have
```rust
Value {
    Bool(bool),
    I64(i64),
    F64(f64),
    Str(String),
    Null,
}
```
or
```rust
Option<Value {
    Bool(bool),
    I64(i64),
    F64(f64),
    Str(String),
}>
```
Which is sorta more how rust normally works.

I don't have a big preference. Though perhaps it would be easier to handle the `Option`.


2
---
Yes, I would be doing `Option<Value>` for both, this would make it easier to handle the code for both in a more similar way.
We can trust that it will always be `Some`, just like we can trust that it will always be `Value::I64`.

If something different is happening things are going wrong.

Can you think of some code where you would use the `Option<Value>` vs `Value` to give a different output/do something different?

**Comment by panarch** [comment]
1
---
Oh interesting.. I'll also think more on this.

As a point of looking NULL in SQL as an one of values, not absence of value, `INTEGER NULL` can be union type of `I64 | Null`. like this..
Then, the first choice may make sense.

When we consider the second,
Though it's not possible to impl on `Option`, but it is still possible using trait approach.
something like this,
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6cb3db25c6a2a6c278d3f8451e6a2bda


Both sounds ok so... I'll spend some more time on it to decider whether.

2
---
> We can trust that it will always be Some, just like we can trust that it will always be Value::I64.

Yeah.. this is really a good point, thanks.
There is already no systematic protection of ensuring type consistency, like forcing `Value::I64` to specific index of row.

> Can you think of some code where you would use the Option<Value> vs Value to give a different output/do something different?

That is also interesting.. I've actually tried hard to think about these cases.
If any sql function only accepts NOT NULL field, then that may be an example.
However, I have no idea. SQL is already born to be with NULL, so...

---
wow.. ok. and thanks, I think your opinion really makes sense...
Let me just have a slight more time on this, if I cannot think any other idea, then let's fix this to do.

And if you have any idea which might be helpful to decide whether `Value::Empty` or `Option<Value>`, please add comment in this thread.
Thanks so much!

**Comment by panarch** [comment]
@KyGost Oh! I think I found a reason of that we need to use `Value::Null` rather than `Option`.

In Option, `None == None` however, `NULL != NULL`.
So by custom implementation of `eq`, we can make `Value::Null != Value::Null` but not possible using `None`.

**Comment by KyGost** [comment]
Yeah, that's a fair point about the `impl`s!

I mean it wouldn't be too bad, it'd probably just be:
```rust
impl Value {
  fn add(self, num: i64) -> self {
    ...
  }
}

impl Option<Value> {
  fn add(self, num: i64) -> self {
    match self {
      None => self,
      Some(value) => value.add(num),
    }
  }
}
```

We could probably set up macros to make it more seemless but it would probably be a bit of cluttery either way.

Hmm, yeah, more thought needed. Will pay more attention in a bit, busy atm.

**Comment by KyGost** [comment]
> @KyGost Oh! I think I found a reason of that we need to use `Value::Null` rather than `Option`.
> 
> In Option, `None == None` however, `NULL != NULL`.
> So by custom implementation of `eq`, we can make `Value::Null != Value::Null` but not possible using `None`.

Oh! Good point!!

**Comment by KyGost** [comment]
Yeah considering the equals and `impl`, I think it might be correct to use `Value::Null` :-)

**Comment by KyGost** [comment]
I think you *could* override the Eq for Option<Value> but that's gross.

**Comment by panarch** [comment]
👍 This is quite.. attractive issue, I'll work on it soon and share!

**Comment by panarch** [comment]
> I think you _could_ override the `Eq` for `Option<Value>` but that's gross.

fyi. Rust does not allow trait impl override. (I actually just tried and found ... 😄 )
