### ISSUE TITLE
Replacing `sqlparser::ast::Value` to custom enum

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#178]
Currently we use `sqlparser::ast::Value` by renaming to `Literal`.
However, in the codes we need only partial part of `ast::Value`.
* `Boolean`, `Number`, `SingledQuotedString` and `Null`
Above four types are all which are used in GlueSQL for now.

It would be good to consider making our own `enum Literal`.

```rust
enum Literal {
    Boolean(bool),
    Number(String),
    Text(String),
    Null,
}
```
the above might be enough.

**Comment by KyGost** [comment]
Would we then just do a function which does a match each time we work with ast values?

**Comment by panarch** [comment]
@KyGost yup, I also expect to do that.
Then we can simply use `data/literal.rs - enum Literal` to take all of them.

**Comment by KyGost** [comment]
That's a good idea :-)
