### ISSUE TITLE
possible to add lmdb as storage backend?

### ISSUE THREAD

**Issue by hiqsociety** [gluesql/gluesql#182]
possible to add lmdb as storage backend?

**Comment by KyGost** [comment]
I can't see why not, want some pointers on where to start? :-)

**Comment by panarch** [comment]
If you have or implement lmdb rust binding, then there's no problem to support lmdb storage backend. :)
Even html5 localStorage can be a storage for GlueSQL. ( https://github.com/gluesql/gluesql-js )
