### ISSUE TITLE
Throw on too many values

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#189]
I've just noticed that this doesn't error, that's a problem:
```sql
INSERT INTO TestUnique (name) VALUES ('test1'), ('test2', 3)
```
Instead it acts like:
```sql
INSERT INTO TestUnique (name) VALUES ('test1'), ('test2')
```

**Comment by panarch** [comment]
```sql
CREATE TABLE TestUnique (
  id INTEGER DEFAULT 1,
  name TEXT
);
```
To test this bug, this above schema can be used.
It needs to have extra column. (here, it is `id INTEGER DEFAULT`).
So, number of values in ('test2', 3) is two but does not exceed the total number of columns in `TestUnique`.

**Comment by ever0de** [comment]
I'll implement it.
