### ISSUE TITLE
INSERT INTO SELECT only works for SELECT *

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#190]
```sql
INSERT INTO TestInsertSelect (name) SELECT name FROM Test
```
Gives
```rust
Err(Value(IncompatibleDataType { data_type: "INT", value: "Str(\"test1\")" }))
```
Discussion on discord: https://discordapp.com/channels/780298017940176946/780298017940176949/826319550537793596

**Comment by panarch** [comment]
Can you write the content? the link to Discord can be good to refer but it is not sufficient.

**Comment by KyGost** [comment]
@panarch 
> Can you write the content? the link to Discord can be good to refer but it is not sufficient.

Fixed

**Comment by KyGost** [comment]
Oops I forgot this wasn't merged yet

**Comment by panarch** [comment]
`INSERT INTO TestInsertSelect (name) SELECT name FROM Test`
Can you provide full example of queries to re-generate?

This works in `src/tests/basic.rs`
`INSERT INTO TestA (id, num, name) SELECT id, num, name FROM Test`
and adding in `basic.rs`
```sql
CREATE TABLE TestB (id INTEGER);
INSERT INTO TestB (id) SELECT id FROM Test;
```
These queries also don't make any noise.

**Comment by KyGost** [comment]
The issue relates to the columns in the insert statement being ignored for the rows in the select query thus resulting in trying to insert all select rows into the table indexed at the 0th position of the table.

I'd rather not write out a full list of testcases for it.

It is resolved in my PR, including test cases.
