### ISSUE TITLE
Function: UUID()

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#196]
`UUID()` is a function which generates a random, unique ID.
[T-SQL Spec for NEWID()](https://docs.microsoft.com/en-us/sql/t-sql/functions/newid-transact-sql)
[MySQL UUID](https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_uuid)
[MySQL UUID Short](https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_uuid-short)

Functions as `UUID_SHORT()` from MySQL.

Future PR?: `BYTES` data type and 128 byte UUID function

Note that, compared to performance of AUTO_INCREMENT, this will be *very* slow.

**Comment by panarch** [comment]
However, is `NEWID()` designed only for `uniqueidentifier`?

More general one to have might be `UUID()`, then we can simply use https://docs.rs/uuid/0.8.2/uuid/

**Comment by KyGost** [comment]
@panarch
Ah! Hmm, not sure whether it would be better to use sled's `generate_id()` or that; thoughts?

**Comment by KyGost** [comment]
And if we did that should the function be called `UUID()`?

I mean we *could* add both

**Comment by panarch** [comment]
Oh this was a different issue, let's forget about `UUID`.
Why are you thinking about replacing `generate_id()`...?

**Comment by panarch** [comment]
`generate_id` is not public api, it should not be exposed as a store trait.

**Comment by KyGost** [comment]
Huh??
Store traits are public?

So what, I'd just do `storage.tree.generate_id()` instead?

**Comment by KyGost** [comment]
> Oh this was a different issue, let's forget about `UUID`.

They'd serve the same purpose, very unique values.

**Comment by panarch** [comment]
For now, I cannot get the point about your intention.
I saw the pr codes and I cannot understand what is purpose of `NEWID`.
Why does we need `NEWID` which is only for `uniqueidentifier` data type in sql server?

**Comment by KyGost** [comment]
It is a random ID, kinda like `AUTO_INCREMENT` but is meant to be cross database.
Functions like UUID.

Enables stuff like creating two parallel tables and unioning them while keeping unique IDs.

**Comment by panarch** [comment]
Then, we can just use `UUID` rather than `NEWID`?
More importantly, implementing uuid functionality and applying to store trait are independent issues. These should be in seperated prs.

**Comment by KyGost** [comment]
Sounds good.

**Comment by panarch** [comment]
ref #364
