### ISSUE TITLE
Omitting NULL column in INSERT is not accepted

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#197]
```sql
CREATE TABLE test (id INT, id_text TEXT NULL);

INSERT INTO test (id) VALUES (1);
-- Err(Row(LackOfRequiredColumn("id_text")))
```

This insert statement should be accepted but it is not.

**Comment by panarch** [comment]
@tmdgusya How about taking this issue for the next one?

Not like the function issue which you've done really well before, it is expected to change only a single file to fix this behavior (+ add test code).
* [src/data/row.rs](https://github.com/gluesql/gluesql/blob/main/src/data/row.rs)

**Comment by tmdgusya** [comment]
> @tmdgusya How about taking this issue for the next one?
> 
> Not like the function issue which you've done really well before, it is expected to change only a single file to fix this behavior (+ add test code).
> 
> * [src/data/row.rs](https://github.com/gluesql/gluesql/blob/main/src/data/row.rs)

ok i take that

it is to changed insert query accepted to null ommitting?

**Comment by panarch** [comment]
@tmdgusya Yes, that's right. you can think that `NULL` option also includes `DEFAULT NULL` if there's no `DEFAULT` value.

**Comment by tmdgusya** [comment]
oh thanks, i understand

I'll fixed that if property of coulumn is NULL then column's set default value null
it's right way?

**Comment by panarch** [comment]
@tmdgusya Yup, 👍

**Comment by boomkim** [comment]
Thanks @tmdgusya to clarify the task. 

Let me follow this issue.

**Comment by ever0de** [comment]
I think I need to close this issue.
Please note #361

**Comment by panarch** [comment]
@ever0de Oh, it looks that `fix #issue` like keyword only works when it exists in the PR content. Thanks :)
