### ISSUE TITLE
String concatenation

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#201]
It would be good to have string concatenation.
Key examples:
[T-SQL allows using the `+` operator on strings.](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/string-concatenation-transact-sql)
[MySQL has the `CONCAT()` function.](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_concat)

**Comment by panarch** [comment]
Thanks! It looks good to have both.

**Comment by panarch** [comment]
I've reviewed several databases and it looks good to follow PostgreSQL's policy.
It implements both ANSI SQL `||` operator and `CONCAT` function.
However, `CONCAT`'s behavior is different from `||`.

`"Foo" || NULL => NULL` but `CONCAT("Foo", NULL) => "Foo"`.
`CONCAT` ignores `NULL` value.

Both can be useful for different purposes.

**Comment by earney** [comment]
This has been implemented in PR #521.  Can we close this issue?
