### ISSUE TITLE
Merging FilterContext and BlendContext

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#203]
Now it is fully ready to do merge `FilterContext` and `BlendContext`.

The only difference between them is that `BlendContext` owns `Row` and `FilterContext` borrows `Row`.
Using `Cow`, both can be unified.

**Comment by KyGost** [comment]
Please note! If you want to and up merging the big changes I've made to the way we `SELECT` this will be a waste of time as I have gotten rid of both of these things.

**Comment by panarch** [comment]
@KyGost Oh, isn't that for the fork you made (https://github.com/SyRis-Consulting/gluesql)?
I didn't know that you are considering to merge to here.

**Comment by KyGost** [comment]
> @KyGost Oh, isn't that for the fork you made (https://github.com/SyRis-Consulting/gluesql)?
> I didn't know that you are considering to merge to here.

**If** it provides notably better performance I would suggest merging it here (to main) as it would be beneficial to all.

Note that any future development I do with/for GlueSQL (assuming that the performance is better) will likely be on top of that branch.

**Comment by panarch** [comment]
@KyGost Ok, as we discussed before, the reason which cannot be merged is not simply the matter of performance.
At least, I don't have any plan to give up no-mut policy and iterator laziness in here.

This is the point.
> Note that any future development I do with/for GlueSQL (assuming that the performance is better) will likely be on top of that branch.

Your current work is already made on top of that branch and the reason you forked was disagreement about strict policies, auto increment, etc between us. It means that any further work on that branch cannot be merged to here.

It's fully ok to have different ideas between us and I really appreciate to your participation and the fork you are doing.
However, branches cannot be merged because neither of us will not change the mind.
