### ISSUE TITLE
Can't Figure Out Proper Implementation For `gluesql::store::Store::scan_data`

### ISSUE THREAD

**Issue by the-wondersmith** [gluesql/gluesql#242]
> Full disclosure, I'm newer to Rust that I'd probably like to admit.

I used converting a parser for DataFlex fixed-width flat-file "databases" I wrote in Python to Rust as a means of actually *learning* Rust. I've got everything working correctly in Rust to read (and eventually write) the "database" files.

I'm trying to implement gluesql's `Store` trait so that I can run queries against the parsed "databases". I'm not getting *something*, and I'm having a hard time wrapping my head around what. I know that's vague, so I'll try to illustrate with code instead.

As it sits now, I have a struct called `DataFlexDB` that is analogous to the directory that contains all of the database files as well as a struct called `DataFlexTable` that represents the actual table. They look like this:

```rust
struct DataFlexTable {
    pub header: Header,
    pub file_path: PathBuf,
}

struct DataFlexDB {
    pub db_path: PathBuf,
    pub tables: Vec<DataFlexTable>,
}
```

Each of the structures provides their own methods for pulling whatever relevant thing you need (the DB can find tables, Tables can find rows, etc...). The `DataFlexTable` struct also has `gluesql`-oriented stuff like:

```rust
impl DataFlexTable {
    
    // ...

    fn schema(&self) -> Option<gluesql::Schema> {
        Some(gluesql::Schema {
            table_name: self.header.file_root_name.to_string(),
            column_defs: self
                .header
                .columns
                .iter()
                .map(|col| col.definition())
                .collect::<Vec<ColumnDef>>(),
        })
    }

    // ...

}

impl<'a> Iterator for DFTableIter<'a> {
    type Item = gluesql::Row;

    fn next(&mut self) -> Option<Self::Item> {
        // ...
    }
}
```

All of which works as advertised. What's got me tripped up is the type checker not being happy with anything I come up with to return from `scan_data`. Clearly I'm misinterpreting how / what `RowIter` is supposed to be. 

What I've got so far is basically just:

```rust
async fn scan_data(&self, table_name: &str) -> Result<RowIter<T>, SqlError> {
    let table = self
        .tables
        .iter()
        .find(|entry| cl_eq(table_name, &entry.header.file_root_name));

    // What now?
    unimplemented!()
}
```

If you were to step through what I've got, you'd have an `Option<&DataFlexTable>` right before the `unimplemented!()` causes a panic. Assuming that unwraps into a table, you'd then be able to call `table.iter()` and have an iterator of proper `gluesql::Row` objects. And I'm absolutely not sure what to do from there.

Hopefully I've illustrated enough with the code above to make up for the vagueness of my explanation. Is there any way someone could point me in the right direction?

**Comment by KyGost** [comment]
For a really simple example of a storage, have a look at MultiSQL's CSV store (note that there is minor differences in implementation between Glue and Multi):
https://github.com/SyRis-Consulting/multisql/tree/main/src%2Fstorages%2Fcsv_storage

**Comment by panarch** [comment]
If `Store` trait is only which you need for now, then you might not need key struct, then you can use `RowIter<T>` using `T as ()`.
Details you provided looks not sufficient for me to understand the point.
However, it seems like that you are currently stuck at code compile.

```rust
pub type RowIter<T> = Box<dyn Iterator<Item = Result<(T, Row)>>>;

/// By implementing `Store` trait, you can run `SELECT` query.
#[async_trait(?Send)]
pub trait Store<T: Debug> {
    async fn fetch_schema(&self, table_name: &str) -> Result<Option<Schema>>;

    async fn scan_data(&self, table_name: &str) -> Result<RowIter<T>>;
}
```
Whatever the internal implementation is used, once you make the return type to trait methods, then code will run.
You don't need to implement `StoreMut` for now, so it can be more simple.
You even might not need to have key, so..
```rust
impl Store<()> for DataFlexStorage {
    async fn fetch_schema(&self, table_name: &str) -> Result<Option<Schema>> {
        ..
    }

    async fn scan_data(&self, table_name: &str) -> Result<RowIter<()>> {
        ..
    }
}
```

For `scan_data`, if you read file using Rust code, then file reader may provide `Iterator`.
You can begin with that `Iterator` and using `map` like methods to change the form to fit `Item = Result<((), Row)>`.

**Comment by the-wondersmith** [comment]
@panarch  Following your advice, I've refactored the `Iterator` implementation on the table reader thusly:

```rust
impl<'a> Iterator for DFTableIter<'a> {
    type Item = gluesql::Result<(gluesql::Value, gluesql::Row)>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.position > self.table.header.record_count || self.table._record_data.is_empty() {
            return None;
        }

        let ret_val = match self
            .table
            .record_from_bytes(&self.table._record_data[self.position as usize])
        {
            Ok(val) => Some(gluesql::Result::Ok((gluesql::Value::I64(self.position as i64), val))),
            Err(_) => None,
        };

        self.position += 1;

        ret_val
    }
}
```

Assuming I'm not *completely* daft, the signature should now correctly match `Iterator<Item = gluesql::Result<(T, gluesql::Row)>>` wherein `T = Value`. If I understood your advice correctly (which the compiler appears to be *insisting* I haven't), the implementation of `Store` should be something like:

```rust
#[async_trait(?Send)]
impl gluesql::Store<gluesql::RowIter<Value>> for DataFlexDB {
    async fn fetch_schema(&self, table_name: &str) -> gluesql::Result<Option<gluesql::Schema>> {
        // ....
    }

    async fn scan_data(&self, table_name: &str) -> gluesql::Result<gluesql::RowIter<Value>> {
        let db_file = self.tables.iter().find(|entry| cl_eq(table_name, &entry.header.file_root_name));

        if let Some(table) = db_file {
            return gluesql::Result::Ok(Box::new(table.iter()));
        }

        panic!()
    }
}
```

The compiler, however, is yelling at me about:

```text
error[E0277]: `(dyn Iterator<Item = Result<(gluesql::Value, gluesql::Row), gluesql::Error>> + 'static)` doesn't implement `Debug`
    --> src/lib.rs:1173:6
     |
1173 | impl Store<RowIter<Value>> for DataFlexDB {
     |      ^^^^^^^^^^^^^^^^^^^^^ `(dyn Iterator<Item = Result<(gluesql::Value, gluesql::Row), gluesql::Error>> + 'static)` cannot be formatted using `{:?}` because it doesn't implement `Debug`
     | 
    ::: ./.cargo/registry/src/github.com-1ecc6299db9ec823/gluesql-0.6.0/src/store/mod.rs:21:20
     |
21   | pub trait Store<T: Debug> {
     |                    ----- required by this bound in `Store`
     |
     = help: the trait `Debug` is not implemented for `(dyn Iterator<Item = Result<(gluesql::Value, gluesql::Row), gluesql::Error>> + 'static)`
     = note: required because of the requirements on the impl of `Debug` for `Box<(dyn Iterator<Item = Result<(gluesql::Value, gluesql::Row), gluesql::Error>> + 'static)>`
```

So I'm pretty sure I've still got something wrong, and I'm 110% positive it's something trivial and silly and I'm gonna feel *real* dumb when you point it out but I'm hoping you'll be gracious enough to do so anyway. 😩

**Comment by panarch** [comment]
Rather than implementing `impl<'a> Iterator for DFTableIter<'a> {`...
It looks like `_record_data` in `&self.table._record_data[self.position as usize]` is shape of `Vec`.
Then, you will be able to simply use `_record_data.into_iter().map(...)` like approach.

Also in the beginning, it would be enough to set `T = ()` you don't need to use `gluesql::Value` for `T`.
```rust
impl Store<RowIter<Value>> for DataFlexDB {
```
This should not use `RowIter<Value>`, if you choose to use `T = Value` then it must be also `Value`.
However, as I mentioned, `()` would be enough.

btw, error message is simple.
generic `T` requires `Debug` but `RowIter<Value>` does not implement `Debug` so it cannot be used as a `T`.

**Comment by the-wondersmith** [comment]
> Rather than implementing `impl<'a> Iterator for DFTableIter<'a> {`...
> It looks like `_record_data` in `&self.table._record_data[self.position as usize]` is shape of `Vec`.
> Then, you will be able to simply use `_record_data.into_iter().map(...)` like approach.

`_record_data` *is* a vec, but it's not parsed or usable as is (it's a `Vec<u8>`). It's basically just an internal cache of the unparsed record data, it's sort of a side-effect of the way the tables are structured and therefore loaded that I'm taking advantage of to reduce... well *effort* duplication really. The records are actually parsed out into usable `gluesql::Row` objects by `record_from_bytes()` which is what the `Iterator` implementation uses as well.

I apologise *so* hard that this just isn't clicking for me yet, but could I ask you to give me the "correct" versions of these two lines for your suggestion of `T = ()` ?

```rust
impl gluesql::Store<gluesql::RowIter<Value>> for DataFlexDB {   // <---- this line
    // ....

    async fn scan_data(&self, table_name: &str) -> gluesql::Result<gluesql::RowIter<Value>> {   // <---- and this line
        // ....
    }
}
```

**Comment by panarch** [comment]
No problem, `T` is used for key representation and that `T` is used when you update data using queries like.. `INSERT`, `DELETE` or `UPDATE` which requires `StoreMut`.
However, you don't need `StoreMut` for now and it means that `T` is not necessary.

```rust
impl gluesql::Store<()> for DataFlexDB {   // <---- this line
    // ....

    async fn scan_data(&self, table_name: &str) -> gluesql::Result<gluesql::RowIter<()>> {   // <---- and this line
        // ....
    }
}
```

`()` just literally means `()`, no value.
You can simply replace all `T`s to `()`.
