### ISSUE TITLE
README.md code example is outdated

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#259]
Current README.md provides..
```rust
...

for query in parse(sqls).unwrap() {
    glue.execute(&query).unwrap();
}
```
This is outdated, not working now in v0.7.

`Glue` module now accepts a raw sql string and execute.
It is enough to use this below,
```rust
glue.execute(sqls).unwrap();
```

**Comment by devgony** [comment]
Let me edit README.md.
I will create Pull-request as soon as finish testing execution of multiple queries!
