### ISSUE TITLE
Implement TRIM function 

### ISSUE THREAD

**Issue by ever0de** [gluesql/gluesql#267]
- Implement TRIM function
- This function is multibyte safe
- Implementing this feature allows to perform the following actions

1.  Remove whitespaces from prefixes and suffixes
    - If only str parameter
    - [rust/std/str/trim](https://doc.rust-lang.org/stable/std/primitive.str.html#method.trim)
    - In the example above, consideration of `\t` should also be considered
2. If the specifier is `BOTH`, Remove the specifier parameter to the prefix and suffix
    - @panarch Please check the contents below
    - `SELECT TRIM(BOTH 'xyz' FROM 'xyzybarxzxxz');`
    -  The result values for this query are different and which method do you want to adopt?
    1. PostgreSQL
        - `bar` 
    2. MySQL
        - `ybarxzxxz`
3. If the specifier is `LEADING`, Remove the specifier parameter to the prefix
    - `SELECT TRIM(LEADING 'xyz' FROM 'xyzybarxzxxz');`
    1. PostgreSQL
        - `barxzxxz`
    2. MySQL
        - `ybarxzxxz`
4. If the specifier is `TRAILING`, Remove the specifier parameter to the suffix
    - `SELECT TRIM(TRAILING 'xyz' FROM 'xyzybarxzxyz');`
    1. PostgreSQL
        - `xyzybar`
    2. MySQL
        - `xyzybarxz`

## A point of caution
- If none of the specifiers BOTH, LEADING, or TRAILING is given, `BOTH` is assumed
- Which adopt, PostgreSQL or MySQL

### PostgreSQL
```sql
trim(both 'xyz' from 'yxTomxx') → Tom
```

- This is a non-standard syntax for `trim()`
    - @panarch Don't have to support?

```sql
trim(both from 'yxTomxx', 'xyz') → Tom
```

### MySQL
```sql
SELECT TRIM('  bar   ')  -> bar
SELECT TRIM(LEADING 'x' FROM 'xxxbarxxx') -> barxxx
SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx') -> bar
SELECT TRIM(TRAILING 'xyz' FROM 'barxxyz') -> barx
```

## Reference

- [PostgreSQL](https://www.postgresql.org/docs/13/functions-string.html)

![image](https://user-images.githubusercontent.com/27040963/128597181-bbc82f70-2c01-4343-ac41-d2e0996d1e84.png)

- [MySQL](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_trim)

![image](https://user-images.githubusercontent.com/27040963/128597152-b66b97b7-282e-49f1-a51b-0828c16b04b8.png)

**Comment by ever0de** [comment]
If adopted, I will also fill out the remaining std functions for 2,3,4 features

**Comment by ever0de** [comment]
Unfortunately, "specifier" of "sqlparser-rs" was not implemented. Let's just implement `feature 1`, which is a function of `TRIM(str)`.

**Comment by ever0de** [comment]
I'll add it to MySQL action.
MySQL can't perform multiple operations at once.

example 
```sql
SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx  ') -> `barxxx`
SELECT TRIM(BOTH 'x' FROM '     xxxbarxxx  ') -> `xxxbarxxx `
SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx') -> `bar `
```

If exits whitespaces, string can't be erased.

**Comment by ever0de** [comment]
Thank you for opening it up again.

## Check List
- [x] Remove whitespaces from prefixes and suffixes
- [ ] If the specifier is BOTH, Remove the specifier parameter to the prefix and suffix
- [ ] If the specifier is LEADING, Remove the specifier parameter to the prefix
- [ ] If the specifier is TRAILING, Remove the specifier parameter to the suffix

**Comment by panarch** [comment]
fyi. while I was just checking `SUBSTRING` behavior, I found that how `FROM` keyword is supported by `sqlparser-rs`

* https://github.com/ballista-compute/sqlparser-rs/blob/e5991f3ae50ee3ee90ef3ddde9b4cb3a0914d85a/src/parser.rs#L628-L647
* https://github.com/ballista-compute/sqlparser-rs/blob/e5991f3ae50ee3ee90ef3ddde9b4cb3a0914d85a/src/parser.rs#L347-L367

```rust
    pub fn parse_substring_expr(&mut self) -> Result<Expr, ParserError> {
        // PARSE SUBSTRING (EXPR [FROM 1] [FOR 3])
        self.expect_token(&Token::LParen)?;
        let expr = self.parse_expr()?;
        let mut from_expr = None;
        let mut to_expr = None;
        if self.parse_keyword(Keyword::FROM) {
            from_expr = Some(self.parse_expr()?);
        }
        if self.parse_keyword(Keyword::FOR) {
            to_expr = Some(self.parse_expr()?);
        }
        self.expect_token(&Token::RParen)?;


        Ok(Expr::Substring {
            expr: Box::new(expr),
            substring_from: from_expr.map(Box::new),
            substring_for: to_expr.map(Box::new),
        })
    }
```

I didn't know enough about the internal sqlparser-rs parsing codes, I was just using it.
Now, I also get motivated by that you are getting interested on adding new features to `sqlparser-rs`, thanks :)
At a glance, it seems quite straightforward though number of lines are above 3,000..

**Comment by ever0de** [comment]
Wow, thank you for motivating me, too.
Let me double check.

**Comment by panarch** [comment]
ref. https://github.com/ballista-compute/sqlparser-rs/pull/331

**Comment by ever0de** [comment]
There are currently two problems.
1. sqlparser does not support non-standard.
1.1 This should be supported according to the respective dialect.
1.2 However, implementation is put on hold by too many dialects.

2. `[ LEADING | TRAILING | There is no dependency between BOTH ]` <-> `[ characters text ]`.
2.1 This also needs to be fixed in sqlparser. Proceed with revision 1.
