### ISSUE TITLE
Separate `sled-storage` to new workspace

### ISSUE THREAD

**Issue by djKooks** [gluesql/gluesql#275]
Hello,

Currently implementation of `sled` wrapper is being offered as default, and kept inside the project.
But because `gluesql` is sql db engine for multiple storage system, it will be better to separate `sled` implementation for new workspace. It can be better to make project more common, and `sled` wrapper can be used as a reference for other storage wrapper in future 🤔

**Comment by panarch** [comment]
I agree and like this so much, sounds really good and thanks a lot for the suggestion. 👍

**Comment by djKooks** [comment]
@panarch thanks~will try to make draft first 🙏

**Comment by djKooks** [comment]
@panarch  hello~
I've created temporary repo, which includes `storage` part of the project.
https://github.com/djKooks/gluesql-sled-storage

There are lot of errors, but just want to share how I think about separation of sled-storage.

Currently I'm thinking of making `SledStorage` class to be separated. So it will be

```
use gluesql_sled_storage::storages::SledStorage;

pub struct Glue {
    pub storage: Option<SledStorage>,
}
```

How do you think?

**Comment by panarch** [comment]
@djKooks Thanks, frequent sharing really helps us to work on it.
It is workspace, so `SledStorage` is still supposed to be in the GlueSQL main repo.
Expected directory structure would be like this..
```
// current
/src/storages/sled_storage/ ...

// new
/src/...
/storages/sled_storage/...
```

`sled_storage` moves outside of `src/` directory, and it can be in `/storages/sled_storage/` as a [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) shape.
Same repo but separate `Cargo.toml`.

**Comment by djKooks** [comment]
@panarch thanks for confirm! So is it like:
```
├── Cargo.lock    // current one
├── Cargo.toml    // current one
├── src/    // current one
├── target/    // current one
└──  storages/
          └──  sled_storage/
                         └──  Cargo.toml
         └──  some_other_storage/
                         └──  Cargo.toml

```
?

**Comment by panarch** [comment]
@djKooks Yup exactly :)
Now, there's only one storage so you might not feel easy to make common storage wrapper. I'll try to prepare in-memory storage soon, then it would be helpful to think about common interface design.

**Comment by djKooks** [comment]
@panarch hello
This is a draft PR for this issue(still lot of things to do) => https://github.com/gluesql/gluesql/pull/288

If there's anything to check, please let me know.

**Comment by djKooks** [comment]
@panarch I've just checked your PR for in-memory storage, and have some question.
In this PR seems directory looks like

```
├── target/    // current one
└── storages/
      └── mod.rs 
      └── in_memory/
             └──  mod.rs ...
```
and no separate `Cargo` file in each storage.

So are you thinking of when somebody wants to use `in_memory` version of gluesql, to make install as

```
[A]
gluesql = { version = "0.x", features = ["in_memory"] }
```
or such as
```
[B]
gluesql = { version = "0.x" }
gluesql-in-memory = 0.x
```

which one is correct?

**Comment by panarch** [comment]
Memory storage just follows current directory structure, so you don't need to be bother by that.
Currently, I'm also not sure what would be the proper structure to do so..
After you've done applying `workspace`, then I'll also apply the same pattern to memory storage.

The answer for the question is certainly [A]
> [A]
gluesql = { version = "0.x", features = ["in_memory"] }

**Comment by djKooks** [comment]
@panarch thanks for confirm.
Please also review here when you have time 🙏 
https://github.com/gluesql/gluesql/pull/288

- How do you think of workspace directory style?
- Please let me know how to test this change
> `cargo test --no-default-features --features sled-storage --verbose` will not work. How should I change this?

**Comment by panarch** [comment]
Ah, ok. What I thought was "workspace", it literally workspace.

https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

Each workspace can have it's own `Cargo.toml` but it does not mean that it has it's own version.
I also hope that I can provide detailed direction about this, but I'm also not sure what it can be possible to do. I also need to spend time for figuring out what to do.

I don't get it why `cargo test --no-default-features --features sled-storage --verbose` will not work, can you provide more details?

**Comment by djKooks** [comment]
@djKooks 
> I don't get it why cargo test --no-default-features --features sled-storage --verbose will not work, can you provide more details?
oh, it's my mistake. Ignore this part.

I'm trying to follow the structure you're doing in for in-memory storage. Will share if there's a progress 🙏

**Comment by djKooks** [comment]
@panarch changed to https://github.com/gluesql/gluesql/pull/346 🙏

**Comment by djKooks** [comment]
Refactored by https://github.com/gluesql/gluesql/pull/442
