### ISSUE TITLE
Implement Function: LTRIM, RTRIM

### ISSUE THREAD

**Issue by devgony** [gluesql/gluesql#282]
# Implement Function: LTRIM, RTRIM

### LTRIM

```sql
-- postgresql ltrim
ltrim ( string text [, characters text ] ) → text
ltrim('zzzytest', 'xyz') → 'test'
```

### RTRIM

```sql
-- postgresql rtrim
rtrim ( string text [, characters text ] ) → text
rtrim('testxxzx', 'xyz') → 'test'
```

### `trim_start_matches` for LTRIM

```rust
pub fn trim_start_matches<'a, P>(&'a self, pat: P) -> &'a str
where
    P: Pattern<'a>,
```

Returns a string slice with all prefixes that match a pattern repeatedly removed.

The [pattern](https://doc.rust-lang.org/std/str/pattern/index.html) can be a `&str`, [char](https://doc.rust-lang.org/std/primitive.char.html), a slice of [char](https://doc.rust-lang.org/std/primitive.char.html)s, or a function or closure that determines if a character matches.

⇒ **_Should use `a slice of chars` as the pattern to implement postgresql LTRIM_**

## This issue will cover...

1. Add LTRIM(), RTRIM() at `ast/function.rs` 
2. Add LTRIM(), RTRIM() at `translate/function.rs`
3. Implement LTRIM(), RTRIM() at `executor/evaluate/mod.rs`
4. Implement test cases at `src/tests/function/`
5. Should pass `cargo check`, `cargo fmt`, `cargo clippy —all-targets`, `cargo test`

## References

1. [https://www.postgresql.org/docs/13/functions-string.html](https://www.postgresql.org/docs/13/functions-string.html)
2. [https://doc.rust-lang.org/std/string/struct.String.html#method.trim_start_matches](https://doc.rust-lang.org/std/string/struct.String.html#method.trim_start_matches)

**Comment by ever0de** [comment]
Shouldn't it be closed?

**Comment by panarch** [comment]
@ever0de Thanks!
