### ISSUE TITLE
Support Function :: ABS, SIGN

### ISSUE THREAD

**Issue by Goinging98** [gluesql/gluesql#283]
# Support Fuction :: `ABS`, `SIGN`

## ABS
`ABS` is to calculate the absolute value of a number.
Return type will be same as input.
```
-- Reference from Postgresql 
select ABS(-15.5);    -> 15.5
select ABS(50 - 100); -> 50 
```

## SIGN
`SIGN` is for sign of the argument (-1, 0, +1)
Return type will be same as input.
```
-- Reference from Postgresql 
select sign(-8.4);  -> -1 
select sign(0);     -> 0 
select sign(8.4);   -> 1
```

## Reference from ..
1. https://www.postgresql.org/docs/9.1/functions-math.html
2. https://www.postgresqltutorial.com/postgresql-abs/

**Comment by earney** [comment]
pull request #510 implements this issue.  I believe it can be closed.

**Comment by Goinging98** [comment]
Thank you!
