### ISSUE TITLE
Implement Function: REPEAT

### ISSUE THREAD

**Issue by inhwa1025** [gluesql/gluesql#284]
# 🚀Implement Function: REPEAT

## REPEAT
`REPEAT` repeats string the specified number of times.
```sql
-- postgresql repeat
repeat( string text, number integer ) → text
repeat('Pg', 4) → PgPgPgPg
```
If number is less than 1, the `REPEAT` function will return an empty string.

## Reference
https://www.postgresql.org/docs/9.1/functions-math.html
https://www.postgresqltutorial.com/postgresql-string-functions/

**Comment by panarch** [comment]
#352
