### ISSUE TITLE
Support `SELECT` without table

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#286]
```sql
SELECT 1;
SELECT 1 + 2;
SELECT "id" || "wow";
```

Currently `SELECT {expr}` queries without referring table are not supported, `translate` module generates `LackOfTable` error.
Let's add this `SELECT {expr};` query support, then we can remove `LackOfTable` error.

**Comment by earney** [comment]
Oracle solves this problem by introducing a table called dual, that contains only one row of dummy data.  The easiest way to implement something similar to a "select without table" would be to duplicate the dual table functionality.  To do this, every time a new database is created, we automatically create a table called dual (or some other name).  This maybe a band-aid solution, but oracle databases have survived just fine for decades with this solution.
Is there a way to make a table read only?  We wouldn't want a "dual" table to be modified in any way.
What do you guys think?  if you are okay with the idea, is a dual a good name or should we use another name?

**Comment by devgony** [comment]
@panarch @genieCS if there is no more progress, may i take this?

**Comment by genieCS** [comment]
@panarch @devgony as I'm not working on this more, unassigned myself😛
