### ISSUE TITLE
Implement modulo(`%`) binary operator

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#299]
e.g.
```
12 % 3 = 4
10 % 12 = 10
..
```

Following tasks are expected to be done
* add `fn modulo` to `data/value/mod.rs`
You can also add unit tests of this new `modulo` fn, there's a existing test case named `arithmetic` and you can use it.

* add `fn modulo` to `data/literal.rs`
Similar to `Value`, but.. there's lack of unit tests though it is required.
You need to add a new one.

* add `fn modulo` to `execute/evaluate/evaluated.rs`

* add integration test cases of modulo to `src/tests/arithmetic.rs`
Here you can also cover code branches of `evaluated.rs` by adding `%` test cases to `arithmetic`.

ref https://github.com/gluesql/gluesql/pull/295

**Comment by MRGRAVITY817** [comment]
I'll do those tasks 👍
