### ISSUE TITLE
Wrapper function for `SledStorage::check_retry`

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#301]
`match` statement with `check_retry` appears many times in `store_mut.rs`, `index_mut.rs` and `alter_table.rs`.
We can add a shared function to wrap this statement.

https://github.com/gluesql/gluesql/blob/bfb89fb6a1666885261a33bf4aaf86b09a340d05/src/storages/sled_storage/store_mut.rs#L59-L63

https://github.com/gluesql/gluesql/blob/bfb89fb6a1666885261a33bf4aaf86b09a340d05/src/storages/sled_storage/index_mut.rs#L131-L135

https://github.com/gluesql/gluesql/blob/bfb89fb6a1666885261a33bf4aaf86b09a340d05/src/storages/sled_storage/alter_table.rs#L137-L141

**Comment by ever0de** [comment]
How about making a Trait that does retry?

ex) 
```rust
trait RetryStore {...}
