### ISSUE TITLE
Update binary operator `/` to return custom error when the divisor is zero.

### ISSUE THREAD

**Issue by MRGRAVITY817** [gluesql/gluesql#306]
Current implementation for binary operator `/` panics out when the divisor is `0`. 
```console
[SQL] SELECT * FROM Arith WHERE 10 / 0 = id;
thread 'arithmetic' panicked at 'attempt to divide by zero', src/data/literal.rs:236:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I think it would be nice to return a custom error for this.

This should also be considered when implementing `%` operator #299

**Comment by panarch** [comment]
Sounds so good! and it would be good to make a separate PR for this issue then I'll quickly review and merge it. Thanks for reporting.

**Comment by MRGRAVITY817** [comment]
@panarch Since this issue is resolved, I think it should be closed.

**Comment by panarch** [comment]
Oh I missed it, thanks a lot!
