### ISSUE TITLE
`PRIMARY KEY` not supported error is required

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#308]
`PRIMARY KEY` is not supported yet.
However GlueSQL allows `CREATE TABLE SingleItem (id INTEGER PRIMARY KEY)` but do nothing for `PRIMARY KEY` attr.
Until the feature is implemented, it should be an error.

It is expected to play with codes in https://github.com/gluesql/gluesql/tree/main/src/executor/alter

**Comment by heka1024** [comment]
I'll try it!
