### ISSUE TITLE
Implement Function: `EXTRACT()`

### ISSUE THREAD

**Issue by simple6192** [gluesql/gluesql#320]
Trying to add Date/Time function `EXTRACT() `

`EXTRACT( A )` : Extract year, month, day, hour, minute, second from timestamp, time, date, interval
```
ex. SELECT EXTRACT(YEAR FROM TIMESTAMP '2016-12-31 13:30:15');   -> 2016
SELECT EXTRACT(MONTH FROM TIMESTAMP '2016-12-31 13:30:15');   -> 12
SELECT EXTRACT(DAY FROM TIMESTAMP '2016-12-31 13:30:15');   -> 31
SELECT EXTRACT(HOUR FROM TIMESTAMP '2016-12-31 13:30:15');   -> 13
SELECT EXTRACT(MINUTE FROM TIMESTAMP '2016-12-31 13:30:15');   -> 30
SELECT EXTRACT(SECOND FROM TIMESTAMP '2016-12-31 13:30:15');   -> 15
```

**Comment by earney** [comment]
now and extract are both implemented in the current version (10.2). 
The reason the above select statements do not work is because [from table] is not optional and a real tablename is required.  Another issue deals with the optional table syntax.
Can we close this issue?
