### ISSUE TITLE
`CAST` from string to `INTERVAL`

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#324]
Current `CAST` function does not support converting from string to `INTERVAL` data type.

https://github.com/gluesql/gluesql/blob/ddef41798fddf067d4582e0a3e683366f023fc45/src/executor/evaluate/evaluated.rs#L141-L150

Two cast functions are expected to be updated.
+
* cast in `Value` - it would be good to add new casts to unit tests in the [value/mod.rs](https://github.com/gluesql/gluesql/blob/main/src/data/value/mod.rs)
There is `fn cast` unit test in the below.
* cast in `data/value/literal.rs`
Good to add literal cast tests to [tests/function/cast.rs](https://github.com/gluesql/gluesql/blob/main/src/tests/function/cast.rs)

It is similar with  https://github.com/gluesql/gluesql/issues/317 but handling `Interval` data is a bit different so it would be also fun to work on it :)

**Comment by devgony** [comment]
Let me try to fix this issue!
