### ISSUE TITLE
Change table_name type from `&str` to `ast::ObjectName`

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#336]
Current parser supports dot(.) separated table name but GlueSQL does not support it.

https://github.com/gluesql/gluesql/blob/76a848514e8fff909bce524736b25d5cc74252b1/src/data/table.rs#L52-L56

There is no special reason not to use `ObjectName`.
This issue is for replacing all `&str` typed `table_name` to use `ObjectName`.
Store trait method param changes are also required.

**Comment by pythonbrad** [comment]
@panarch, it appears that this issue is old. The issue is still available?

**Comment by panarch** [comment]
@pythonbrad Oh thanks! Now we no longer use `ObjectName` so yes this issue is not available.
