### ISSUE TITLE
Apply `bigdecimal` feature to `sqlparser-rs`

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#337]
`sqlparser-rs` provides `bigdecimal` as an optional feature.
Currently, `bigdecimal` is not being used in here.
So `Literal::Number` contains `String`, but it would be better to use `bigdecimal`.
Then, we don't need to parse `String` to `i64` or `f64` in execution layer.

In https://github.com/gluesql/gluesql/blob/main/src/data/literal.rs
We can clean up all binary operations between number values.

**Comment by devgony** [comment]
Let me try it!
