### ISSUE TITLE
Simplify `evaluate_function` codes by adding macros

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#349]
This issue is to simplify `Nullable` enum control flow using declarative macro.

https://github.com/gluesql/gluesql/blob/de7310602376533f2dee87a863841f225f729179/src/executor/evaluate/mod.rs#L175-L191

When `Nullable::Null` comes, it always returns `Ok(Evaluated::from(Value::Null))`.
However, that result is also kind of success `Ok`. It cannot be handled by try operator `?`.
It would be good to use macro until [rfcs/3058-try-trait-v2.html](https://rust-lang.github.io/rfcs/3058-try-trait-v2.html) comes to Rust stable.

e.g.
https://github.com/gluesql/gluesql/blob/de7310602376533f2dee87a863841f225f729179/src/executor/evaluate/mod.rs#L225-L229

We can change the above like this,
```rust
Function::Lower(expr) => {
    let v = eval_to_str!(expr).to_lowercase();

    Ok(Evaluated::from(Value::Str(v)))
}
```

It is expected for us not to handle `Nullable` enum explicitly.

**Comment by vbbono** [comment]
Thanks! Assign to me :D
