### ISSUE TITLE
`XOR` binary operator support

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#354]
ref. https://mariadb.com/docs/reference/mdb/operators/XOR/

This is a logical operator `XOR` (not bitwise) which accepts two boolean expressions and return boolean value.
Unlike `MariaDB` reference, it would be enough not to consider numeric values. Let's just accept only boolean values.

`{boolean} XOR {boolean}` => `{boolean}`
```
TRUE XOR FALSE => TRUE
TRUE XOR TRUE => FALSE
```

#### Add `XOR` binary op to `sqlparser-rs` (prior issue)

ref. https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/ast/operator.rs

`sqlparser-rs` does not support `XOR` yet.
Prior to work on adding `XOR` here, contribution to `sqlparser-rs` is required.

**Comment by zmrdltl** [comment]
i'll do this!

**Comment by panarch** [comment]
ref. https://github.com/gluesql/gluesql/pull/359
