### ISSUE TITLE
Implement `prelude` for userside APIs

### ISSUE THREAD

**Issue by MRGRAVITY817** [gluesql/gluesql#378]
## `lib.rs` is exporting relentlessly...
Currently all modules are exported like this from `lib.rs`.
![image](https://user-images.githubusercontent.com/41038636/136666994-3cc18d99-b331-4d31-842a-638860152507.png)

This can cause situations like importing `Value` from `crate::Value` or `crate::data::Value`, which can be confusing.
Maybe it's time to: 

- [ ]  Extract userside APIs (`data::Value`, `Result`, `Error`, `Glue` etc) into the `prelude`
- [ ] Refactor `lib.rs` to remove unnecessary exports.

## Reference
https://doc.rust-lang.org/std/prelude/index.html

**Comment by ever0de** [comment]
ref #388
