### ISSUE TITLE
Support `INT(32)` data type

### ISSUE THREAD

**Issue by heka1024** [gluesql/gluesql#384]
Like `MySQL` and `PostgreSQL`, many sql engines support a wide range of integers. For example, `MySQL` has a numeric type `TINYINT` which range is -128 to 127. Like this, it would be nice if we support such a wide range of integers.

**Comment by kevingzhang** [comment]
If I need to use UINT(128), I know GlueSQL currently doesn't support 128bit int. Is there any workaround for this?
thank you in advance

**Comment by ever0de** [comment]
> If I need to use UINT(128), I know GlueSQL currently doesn't support 128bit int. Is there any workaround for this? thank you in advance

<https://github.com/gluesql/gluesql/issues/482>

It will be added when the next task is completed.
thank you

**Comment by panarch** [comment]
Thanks to @earney 
resolved in #608
