### ISSUE TITLE
Support `Expr::MapAccess`

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#394]
sqlparser-rs v0.11 now supports nested map access.
ref. https://github.com/sqlparser-rs/sqlparser-rs/pull/356

e.g.
```sql
SELECT a["b"]["c"][0]["d"]["abc"] FROM TableA;
```
SQL query like above is now accepted by the parser.
This issue is to add support `Expr::MapAccess` to `MAP` and `ARRAY` types.

There already exists similar GlueSQL specific function with name of `UNWRAP`.
We can use different behavior for `MapAccess`.
`UNWRAP` basically does not generate error when accessing out-of-index of key-not-found cases, it simply returned `Value::Null`.
Unlike `UNWRAP`, it would be good to return error for invalid access on `Expr::MapAccess { .. }`

another ref. https://github.com/gluesql/gluesql/blob/main/src/data/value/selector.rs

**Comment by Snowapril** [comment]
If there is nobody working on this issue, can I try this? 😊

**Comment by ever0de** [comment]
> If there is nobody working on this issue, can I try this? 😊

Because there is no issue manager, It seems like you are free to work on it first.
Even if it was working, the maintainer would have been working on it.

**Comment by panarch** [comment]
Sure!

**Comment by ever0de** [comment]
ref #827

**Comment by panarch** [comment]
resolved in #827
