### ISSUE TITLE
Add examples for `MemoryStorage`

### ISSUE THREAD

**Issue by MRGRAVITY817** [gluesql/gluesql#398]
Current files in `examples` are focused on using `SledStorage`.
Users might want to know how to use `MemoryStorage`.

**Comment by pythonbrad** [comment]
Please @MRGRAVITY817 , can i have more explanation about it?

**Comment by ever0de** [comment]
Just adding an example for memory storage in a folder at <https://github.com/gluesql/gluesql/tree/main/examples>

**Comment by pythonbrad** [comment]
Ok thanks.
