### ISSUE TITLE
Support `SetExpr::Values` in `select` module

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#417]
Current `select` module does not support `SetExpr::Values`
ref.
https://github.com/gluesql/gluesql/blob/874710024e5a3d6df7925a834ac80927433f7445/src/executor/select/mod.rs#L161-L172

However, it is already being implemented and used in handling `INSERT` query.
https://github.com/gluesql/gluesql/blob/874710024e5a3d6df7925a834ac80927433f7445/src/executor/execute.rs#L171-L176

Let's merge this `SetExpr::Values` handler into `select` module.

**Comment by devgony** [comment]
Let me try this issue!
