### ISSUE TITLE
Update aggregate functions to support `Expr`

### ISSUE THREAD

**Issue by zmrdltl** [gluesql/gluesql#423]
## Description
The [get_value](https://github.com/gluesql/gluesql/blob/main/core/src/executor/aggregate/state.rs#L241) of the existing `closure of function accumulate` determines the value after parsing the parameter to be entered into the function in the enum `Expr`.  It supports only some of the Expr syntax and returns a value, otherwise it returns an error.

Currently supported parameter
1. `Expr::Identifier`
2. `Expr::CompoundIdentifier`
3. `wildcard for function COUNT`
</br>

Therefore, it is necessary to change the aggregate function to support all expressions as a parameter

**Comment by panarch** [comment]
e.g.
```sql
/* Supported */
SUM(id)
COUNT(*)
MAX(col),
MIN(ta.col2)

/* To be supported */
SUM(id + 1)
MAX(col + col2)
SUM(id * rate)
```

**Comment by earney** [comment]
This issue is also discussed in issue #151
