### ISSUE TITLE
Supports arithmetic operation between Decimal and primitive types

### ISSUE THREAD

**Issue by ever0de** [gluesql/gluesql#427]
ex)
- Decimal + i64 = Decimal
- Decimal + f64 = Decimal 
...

**Comment by earney** [comment]
I believe this has been resolvedi in PR #530, which has been merged.  Can we close this issue?

**Comment by ever0de** [comment]
> I believe this has been resolved in PR #530, which has been merged. Can we close this issue?

Thanks
