### ISSUE TITLE
Support CAST from other data types to decimal

### ISSUE THREAD

**Issue by ever0de** [gluesql/gluesql#430]
## SQL Example

```sql
CAST("10.2" AS DECIMAL);
CAST(10.2 AS DECIMAL);
...
```

## Solution

- `data/value/into.rs`

Implement `TryInto<Decimal>` for  Value, &Value

- `data/value/mod.rs/cast`

Add try_into from other data types to decimal in cast function

**Comment by earney** [comment]
I believe this issue has been resolved...  see PR #529

**Comment by panarch** [comment]
Thanks 👍 closing this
