### ISSUE TITLE
MVCC Transactions Support

### ISSUE THREAD

**Issue by D1plo1d** [gluesql/gluesql#44]
I can only imagine how large a feature this is but I wanted to put it out there. MVCC Transaction support would empower developer's to prevent reading and writing inconsistent data to gluesql.

I'm guessing however that this is currently blocked on Sled's lack of transactional scan support inside TransactionTrees(?)

**Comment by panarch** [comment]
Ok, in case of sled, you're right. currently sled does not support scan in transaction.
And for now, GlueSQL also does not have transaction feature support yet.
I hope that they implement it not in too late

`Transaction` will be provided as a trait, like existing 2 store traits: `Store` and `StoreMut`.

And precisely, MVCC Transaction is may be a role of storage layer not execution layer which gluesql takes.
So, GlueSQL will provide proper interface may be just named `Transaction` trait.

If any storage implements all three `Store`, `StoreMut` and `Transaction` traits, then it can run all existing sql queries and transaction feature.
But not like `Store` and `StoreMut` traits, I'm currently thinking about making `Transaction` as an optional.

For example... [GlueSQL-js](https://github.com/gluesql/gluesql-js) has another custom storages, one is based on html5 localStorage.  
And localStorage api is too too simple so it's almost not possible to provide `Transaction` support, then it can just implement only 2 traits `Store` and `StoreMut`. It still executes most of sql queries only except for transaction queries something like `BEGIN; COMMIT; ROLLBACK;`.

Future plan is this,
Providing store traits as independent as possible, in the future it will be...
* Store
* StoreMut
* Transaction
* ForeignKey
* Index
* ...

And if someone wants to make their own custom storage, they can pick the whole of them or it's also ok to pick only few of them.
