### ISSUE TITLE
Is it possible to construct an in-memory database from bytes?

### ISSUE THREAD

**Issue by GeeWee** [gluesql/gluesql#452]
Apologize if this is answered in the documentation somewhere, but I was unable to find it.

I have a static set of data, that I would like to be able to index and query efficiently from short-lived processes. (Rust compiled to wasm at Fastly's compute@edge network)

I would like to be able to create my database once, and embed it into my application binary, perhaps by writing it to a file and using `include_bytes!` or similar.
I'd then like to map these bytes into gluesql backed by a `memory` storage.

Is there any way of accomplishing this?

**Comment by panarch** [comment]
Thanks a lot, currently there's no official import/export support by `Store` trait or something else.
In the current structure, it is possible to import/export, but in a very.. bothersome way.

Through this PR(https://github.com/gluesql/gluesql/pull/453), I've applied Serde to `MemoryStorage`, so it would be useful for your use case.

**Comment by GeeWee** [comment]
Awesomet! Thanks. I think that'd be enough for my usecase.
