### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by MichaelMcDonnell** [gluesql/gluesql#46]
Is a command line interface planned? I liked playing around with the web interface but there doesn't seem to be something equivalent for the terminal?

**Comment by panarch** [comment]
I have a plan but I may use a separate repository, but it might take some time to work on cli task.
For now, you can expect same SQL support between Rust crate and web version.
Though they use different storages, they all pass same integration test cases so you can think as same at least about functionality.

**Comment by willy610** [comment]
hej folks.
Just made some kind of console application built on ``gluesql  = {version="0.3"}`` or later of cource. Not on the project source. ok.

It's not present at GitHub yet. Trademarks, maintain, could be separate repository as a sister to gluesql.
It's called abc_sql at the moment to avoid any interferences with gluesql

It has the following poor help
```
here > ./target/debug/abc_sql --help
OK 
abc-sql   --newdb filename
        | --insql file --olddb filename [--printsqlstm]
        | --incsv file --olddb filename --table tablename 
            [ --append ]
            #NOT_YET ( 
              (--headers "col1,col2" [ --ignorefirtslineheaders ] )
              | --headersfirstlineincsv 
            ) 
            #NOT_YET [--colsep ','] [ --linsep ' ']
        | --olddb filename #interactive usage !
        | --outcsv filename --olddb filename --table tablename
        | --outsql filename --olddb filename --table tablename
            [--droptable] [--createtable] 
here > 
```

Create db, import of sql scripts, export of sql, csv import/export and interactive support

Interactive

```
abc-sql  > select * from S                                
         > left join P on S.CITY = P.CITY;
"select * from S left join P on S.CITY = P.CITY ;"


+-----+-------+--------+--------+------+-------+-------+--------+--------+
| SNO | SNAME | STATUS |  CITY  | PNO  | PNAME | COLOR | WEIGHT |  CITY  |
+-----+-------+--------+--------+------+-------+-------+--------+--------+
| S1  | Smith |     20 | London | P1   | Nut   | Red   |     12 | London |
| S1  | Smith |     20 | London | P4   | Screw | Red   |     14 | London |
| S1  | Smith |     20 | London | P6   | Cog   | Red   |     19 | London |
| S2  | Jones |     10 | Paris  | P2   | Bolt  | Green |     17 | Paris  |
| S2  | Jones |     10 | Paris  | P5   | Cam   | Blue  |     12 | Paris  |
| S3  | Blake |     30 | Paris  | P2   | Bolt  | Green |     17 | Paris  |
| S3  | Blake |     30 | Paris  | P5   | Cam   | Blue  |     12 | Paris  |
| S4  | Clark |     20 | London | P1   | Nut   | Red   |     12 | London |
| S4  | Clark |     20 | London | P4   | Screw | Red   |     14 | London |
| S4  | Clark |     20 | London | P6   | Cog   | Red   |     19 | London |
| S5  | Adams |     20 | Athens | null | null  | null  | null   | null   |
+-----+-------+--------+--------+------+-------+-------+--------+--------+

abc-sql  > 

```

It hink it would be very useful for integration tests and it's powerful because you don't need to rebuild a project. 
Just edit your scripts or try out via interactive playing.

Really amusing!

If it sounds interesting I can attach a project zip-file into this issue or elsewhere

**Comment by willy610** [comment]
Attached is a project on a simple command line tool.


[abc-sql.zip](https://github.com/gluesql/gluesql/files/5602666/abc-sql.zip)

**Comment by MichaelMcDonnell** [comment]
That's looks nice @willy610! Are you planning to publish it on a GitHub repository under an open source license?

**Comment by willy610** [comment]
Thanks @MichaelMcDonnell 

Within a week or two I will put on GitHub repository under an open source license.
I hope it won't interfere with this GlueSql in any way. Trademarks or what ever

**Comment by MichaelMcDonnell** [comment]
Sounds good @willy610! The name `abc_sql` makes it clear that it is something separate.

**Comment by panarch** [comment]
@willy610 You can feel comfortable to do what you want, that will not make any issue.
GlueSQL project is under Apache-2.0 license which is very generous, you can do almost whatever under this license.

**Comment by willy610** [comment]
Just published [https://github.com/willy610/abcsql.git](https://github.com/willy610/abcsql.git)

With a tryout on ORDER BY #78

**Comment by panarch** [comment]
@willy610 Thanks for sharing, wow.. looks so great!

**Comment by MichaelMcDonnell** [comment]
I just learned about the [rustyline crate](https://crates.io/crates/rustyline). I think basing a CLI implementation around that would work out great. It has a lot of features including history, line editing and completion.

**Comment by panarch** [comment]
@MichaelMcDonnell Thanks, looks good to use.

I'll also leave another crate [structopt](https://github.com/TeXitoi/structopt), this would be useful for command line argument parsing.
