### ISSUE TITLE
Add a functionality to read-and-execute SQL file in GlueSQL CLI

### ISSUE THREAD

**Issue by MRGRAVITY817** [gluesql/gluesql#481]
## Support SQL file read-and-execute
It would be nice to read `*.sql` files and execute queries inside it.
Below I suggest some usages.
### Using with command line argument
```bash
$ gluesql --execute filename.sql
``` 
### Using inside the GlueSQL CLI
```bash
$ gluesql
[memory-storage] initialized

gluesql> .execute filename.sql
Executed queries in filename.sql

gluesql> .tables
╭────────╮
│ tables │
╞════════╡
│ hello  │
╰────────╯
```

**Comment by earney** [comment]
I believe this enhancement has been implemented and is currently in production.  Can this issue be closed?

**Comment by ever0de** [comment]
> I believe this enhancement has been implemented and is currently in production. Can this issue be closed?

Thanks for the report!
