### ISSUE TITLE
Convert `Store` trait type from Generic Type Parameter to Associated Type

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#483]
1. Remove `Debug` trait bound
2. Convert GTP to Associated Type

Expected change
```rust
pub trait Store<T: Debug> {
...
}
```
to
```rust
pub trait Store {
  type Key;

  ..
}
```

`Debug` trait bound looks not really necessary to be included.

**Comment by MRGRAVITY817** [comment]
> Thanks for @MRGRAVITY817 

My pleasure 😀

**Comment by panarch** [comment]
Now there is a plan to remove `T` at all when adding primary key support. (will replace `T` to use `data::Key`)
Due to this change, neither generic or associated type is needed for Store traits.
