### ISSUE TITLE
IS NULL, IS NOT NULL support

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#50]
```sql
SELECT * FROM Foo WHERE name IS NULL;
SELECT * FROM Bar WHERE name IS NOT NULL;
```

**Comment by leoppro** [comment]
Could I implement it this weekend?

**Comment by panarch** [comment]
Sure 👍 I'm really pleased that you get interested on contribution. 
For the first contribution, here are some info good to know at beginning.

* In case of expanding SQL supports, you need to be familiar with [sqlparser-rs](https://github.com/ballista-compute/sqlparser-rs) which is the parser GlueSQL depends on.
Mainly you need to look at will be `ast/*`, and in this case, it would be `enum Expr` in `ast/mod.rs`.

* `executor/filter.rs` handles `WHERE` clause, so that is where you need to look.
you can add `IS NULL` and `IS NOT NULL` supports.

* Before editing `src/` codes, it would be better to start by adding test cases.
In this case, `src/tests/nullable.rs` is proper position to modify.
Then you can simply test using `cargo test --all-features nullable`.

* After finishing works, then..
```
cargo fmt
cargo clippy --all-features
cargo test --all-features
```
All above commands pass, then it's all done :)  

If there is anything you want to ask or request, then please feel free to write that on this issue thread.  
Good luck!
