### ISSUE TITLE
implement show indexes from table

### ISSUE THREAD

**Issue by ghost** [gluesql/gluesql#520]
implement show index from table syntax

**Comment by earney** [comment]
> Is it correct to support the syntax?
> 
>     * `SHOW INDEXES FROM table_name;`
> 
> 
> assigned to you. thanks for the report

Yes, you are correct.  I'll try to fix the title.

**Comment by earney** [comment]
If I'm viewing sqlparser correctly, it doesn't support show indexes syntax, so I put in an issues with the sqlparser team requesting that enhancement.

**Comment by earney** [comment]
In sqlparser-rs version 0.16, this syntax is supported:

ql: "show indexes from mytable"
AST: [ShowVariable { variable: [Ident { value: "indexes", quote_style: None }, Ident { value: "from", quote_style: None }, Ident { value: "mytable", quote_style: None }] }]

**Comment by earney** [comment]
PR #554  adds a third column to the output (displays expression used to define the index).  Once that PR is merged, this issue can be closed.

**Comment by panarch** [comment]
resolved in #551
