### ISSUE TITLE
Is there a way to do queries without programming it?

### ISSUE THREAD

**Issue by Raj2032** [gluesql/gluesql#524]
For postgres or oracle, you know how you can do queries without having to code it?

is it possible with gluesql by any chance?

**Comment by ever0de** [comment]
> For postgres or oracle, you know how you can do queries without having to code it?

Does this mean you can use the query method of `postgres` or `oracle`?

> is it possible with gluesql by any chance?

gluesql now has a cli function. Here's how to install it:

```shell
cargo install gluesql
gluesql # use memory storage
[memory-storage] initialized
╭─────────────────────────────╮
│ command description │
╞════════==================================
│ .help show help │
│ .quit quit program │
│ .tables show table names │
│ .version show version │
╰─────────────────────────────╯

gluesql>
```

**Comment by Raj2032** [comment]
> Does this mean you can use the query method of postgres or oracle?

Yeah I guess so like for example I type in the prompt:

`select * from table`

in some prompt and it returns the results immediately without having to code.

> gluesql now has a cli function. Here's how to install it:

So in the prompt I can just type `select * from table` and it will immediately return the results?

**Comment by ever0de** [comment]
> So in the prompt I can just type `select * from table` and it will immediately return the results?

Of course, if you have data in the table.

**Comment by Raj2032** [comment]
Ok thanks mate :) @ever0de

**Comment by ever0de** [comment]
can I close it? @Raj2032
