### ISSUE TITLE
Bump `sqlparser-rs` version to 0.16.0

### ISSUE THREAD

**Issue by ever0de** [gluesql/gluesql#525]
It's an internally known issue, but I'm posting it for public notice.

The change in sqlparser is bigger than you think, so it should be taken as a conversion(enhancement) point.

**Comment by earney** [comment]
Do you think it would be better to upgrade one version of sqlparser-rs  from v13 to v14 then from v14 to v15 and then v15 to v16 or just do a jump from v13 to v16?

I did try to modify the Cargo.toml from v13 to v16, and yes, there are a bunch of changes.

**Comment by ever0de** [comment]
> Do you think it would be better to upgrade one version of sqlparser-rs from v13 to v14 then from v14 to v15 and then v15 to v16 or just do a jump from v13 to v16?
> 
> I did try to modify the Cargo.toml from v13 to v16, and yes, there are a bunch of changes.

you're right.
It would be rather easy to go up step by step.
It would be good to think of this as a goal.

**Comment by earney** [comment]
I believe this issue has been resolved.

**Comment by panarch** [comment]
@earney Thanks!
