### ISSUE TITLE
concat function behavior

### ISSUE THREAD

**Issue by earney** [gluesql/gluesql#526]
A question for you all..

Different databases implement the concat function differently.  Some databases return NULL if one or more of the arguments to concat is NULL, while other databases just ignore the NULLS and returns everything else concatenated together.  The current concat implementation that was just merged in the main branch returns NULL if any of the arguments are NULL.
do we want to keep this implementation or should we just ignore the NULL?
there is also a || operator that concatenates two operands together.  If either of the 2 args is NULL, NULL is returned.
I personally am leaning toward modifying the concat function so that it ignores NULLS so that gluesql users can have both options.  If they want NULL returned use ||, or if they want NULLs to be ignored use the concat function.

What do you guys think?

**Comment by panarch** [comment]
I'm for your idea about having different behaviors between `||` and `CONCAT`.
Then, users can choose either of these depending on their needs.

### `||`
* binary operator
* operation between `NULL` returns `NULL`
* converting any non-`Value::Str` value to `Value::Str` and concat

### `CONCAT`
* accepts 1~N params
* Ignore `NULL` and concat
* converting any non-`Value::Str` value to `Value::Str` and concat

**Comment by earney** [comment]
The last merge implements this issue..
