### ISSUE TITLE
JSON type and functions

### ISSUE THREAD

**Issue by jrmuizel** [gluesql/gluesql#549]
[sqlite has these](https://www.sqlite.org/json1.html) so it might be nice to have in glusql too

**Comment by panarch** [comment]
There is a plan to provide better semi-structured and even unstructured data in several months.
For now, some limited functions are supported. You can use `MAP` and `LIST` data types.

e.g. two data types:
- [MAP examples](https://github.com/gluesql/gluesql/blob/main/test-suite/src/data_type/map.rs)
- [LIST examples](https://github.com/gluesql/gluesql/blob/main/test-suite/src/data_type/list.rs)
