### ISSUE TITLE
think about adding github releases

### ISSUE THREAD

**Issue by joseluis** [gluesql/gluesql#58]
It would be very nice for people like me who would like to be notified about version updates, without necessarily having to be notified about issues and PRs :smiling_face_with_three_hearts:

**Comment by panarch** [comment]
That sounds good. Thanks for letting me know, I'll also figure out how to add github action to automate `release` task.
I'm currently planning to bump version after I finish https://github.com/gluesql/gluesql/issues/12
For next versions, I'll use github releases.
Thanks!

**Comment by panarch** [comment]
@joseluis I released v0.1.16 to GitHub release, now you can see the changes between versions easily. 👍
