### ISSUE TITLE
Add `SharedMemoryStorage` to the src documentation comment

### ISSUE THREAD

**Issue by ever0de** [gluesql/gluesql#639]
https://github.com/gluesql/gluesql/blob/1f0f84d59102b5bda01dad7fefeb84bcc7949d67/src/lib.rs#L62-L64

Add `SharedMemoryStorage` to the src documentation comment, and change the github address to the path

**Comment by kim-seo-hyun** [comment]
Please assign it to me :)

**Comment by ever0de** [comment]
The location pointed to is the tests directory, so path cannot be used here.
