### ISSUE TITLE
Support `IndexedDB` for browser

### ISSUE THREAD

**Issue by yujong-lee** [gluesql/gluesql#640]
# Background

There was `Web SQL` in the past, but it has been deprecated since November 2010. Now there are two storage options for the web. One is `Web Storage` and the other is `Indexed DB`. And the latter is suitable for large, structured data.

`IndexedDB` can store a large amount of data asynchronously.  Also, unlike [sql.js](https://github.com/sql-js/sql.js/), data is persisted and continue to work while offline. But we can not use SQL for it. So it is the right place where `GlueSQL` can come in and do a good job.

# Consideration

There won't be much difference in implementation with other storage like [memory storage](https://github.com/gluesql/gluesql/tree/main/storages/memory-storage). But there are two things we should consider before we start.

1. JS Binding
We need a way to interact with [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API). For that, [rexie](https://github.com/devashishdxt/rexie) might be a good option.
2. Schemaless Data
@panarch is planning to rewrite some of the code at the execution layer in GlueSQL. So works before it might need to be rewritten to match the new Storage layer. 

# Plan
1. Implement `Store` and `StoreMut` trait

https://github.com/gluesql/gluesql/blob/1f0f84d59102b5bda01dad7fefeb84bcc7949d67/core/src/store/mod.rs#L74-L98

**Comment by devashishdxt** [comment]
Developer of [`rexie`](https://crates.io/crates/rexie) here, I think a better alternative of `rexie` for low level use cases is [`idb`](https://crates.io/crates/idb).

**Comment by panarch** [comment]
resolved in #1067
