### ISSUE TITLE
Group the import statements

### ISSUE THREAD

**Issue by ever0de** [gluesql/gluesql#646]
We have rules for grouping import statements.
However, there are some places that are not observed from time to time.
Fix this.

## How?

There is one fine-grained rule in [rustfmt](https://github.com/rust-lang/rustfmt) that lets you fix this all at once.
<https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity>

Last but not least, it's still unstable (need to use nightly cargo).
Therefore, it has not been applied yet, and it would be good to use this to correct only the wrong parts.

1. `rustfmt.toml`

```toml
imports_granularity = "One"
```

2. `command`

```shell
cargo +nightly fmt
```

## Points to note

We will formally apply once this is stabilized.
Until then, you will want unstable settings to not exist.

**Comment by ever0de** [comment]
![image](https://user-images.githubusercontent.com/27040963/178908739-22d4b0e8-e3db-4ee8-ba6c-077470484986.png)
Areas to which the found rules do not apply

**Comment by yugeeklab** [comment]
Can I take this issue??

**Comment by ever0de** [comment]
> Can I take this issue??

Sure
