### ISSUE TITLE
question: is array support planned?

### ISSUE THREAD

**Issue by phrohdoh** [gluesql/gluesql#65]
Apologies if you've covered this somewhere already, or if this ought to be asked of `sled`, but are [arrays] planned?

[arrays]: https://www.postgresql.org/docs/current/arrays.html

**Comment by panarch** [comment]
Here is the place to ask, you chose the right one.

That sounds interesting, it can be supported in someday but not expected in near future.
Until GlueSQL supports foreign key, transaction and index, I'll focus on implementing that core functions.
After that I can consider it or someone who gets interested on this issue can participate at any time.
I'll not close this issue and leave for some others.

**Comment by KyGost** [comment]
*Technically* you can already, it is just gross:
Here's what I've been using:
```rust
	pub(crate) fn insert(
		&mut self,
		table: String,
		rows: Vec<Vec<gluesql::parser::ast::Expr>>,
		columns: Vec<Ident>,
	) -> gluesql::Result<Payload> {
		self.db.execute(&gluesql::Query(Statement::Insert {
			table_name: ObjectName(vec![Ident {
				value: table.to_string(),
				quote_style: None,
			}]),
			columns,
			source: Box::new(gluesql::parser::ast::Query {
				ctes: vec![],
				body: SetExpr::Values(Values(rows)),
				order_by: vec![],
				limit: None,
				offset: None,
				fetch: None,
			}),
		}))
	}
```

It would be nicer to have a far more user friendly way though.

**Comment by KyGost** [comment]
I've just realised-- did you mean array data type or array input?

**Comment by ever0de** [comment]
Now supports lists. Can I close the issue?
Merged PR: <https://github.com/gluesql/gluesql/pull/370>
Test code: <https://github.com/gluesql/gluesql/blob/74bfd107b7e5d30ed163d865e5e84efdb4a482c7/src/tests/data_type/list.rs>

**Comment by panarch** [comment]
In fact, it is a bit different.
`LIST` allows any `Value` for its element.
However, `ARRAY` type only allows same type for every element.

`INTEGER[]` -> integer array
`LIST` -> any `Value` can be in the `LIST`.

However, there's no plan for supporting same type array datatype for now.
I'll close this, and we can consider whether to support array type or not later if other user requests.
