### ISSUE TITLE
Add Assignees automatically when someone creates PR

### ISSUE THREAD

**Issue by 24seconds** [gluesql/gluesql#667]
## Description

Currently in the gluesql when the PR is created by someone - let say Bob, then gluesql maintainers manually assign the Bob as `Assignees` section - which is quite cumbersome. So it is good to let bot add assignees. I remember there was a github action which exactly supports this.

**Comment by garimellasrisudha** [comment]
yes i have idea on this we can do this in settings in codeowners part .
in project setting we can add codeowners and in branch setting we tick that codeowners

**Comment by 24seconds** [comment]
> yes i have idea on this we can do this in settings in codeowners part . in project setting we can add codeowners and in branch setting we tick that codeowners. As i can't able to see settings near repo because i don't have access

Ah, thank you for the comment. As I understand what you are talking about is [CODEOWNER](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners). When we set the CODEOWNER then the person who has a responsibility about specified path in CODEOWNER file will be added as reviewer automatically.

What I want to do is to add `pr writer` automatically as Assignees - see the image below. So it's quite different I think
![image](https://user-images.githubusercontent.com/34280965/180593577-486cd9a7-31d2-42f1-bbe5-1a007ab1fccd.png)

**Comment by gimwonbae** [comment]
Can I work on this issue? Kindly assign it to me!
