### ISSUE TITLE
[AST Builder] refactor `ast_builder::expr::binary_op`

### ISSUE THREAD

**Issue by bugoverdose** [gluesql/gluesql#678]
## Background 

Clean code is something we should keep pursuing forever.

When I first saw `ast_builder::expr::binary_op`, it was kind of hard to figure out which functionalities were already implemented and which were not. So I first want to cleanse/organize the entire file to make it more readable.

## Task

1. Make the order of `Eq`, `Gt`, etc match the order of `BinaryOperator` at `ast::operator`.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/73531614/180760125-b9c97ace-8172-4095-812a-ebcf76185df8.png">

2. Divide the unit tests to different test methods and order them to match the order of `BinaryOperator` at `ast::operator`, like the format below. 

```rust
    #[test]
    fn add_op() {
        let actual = col("id").add(10);
        let expected = "id + 10";
        test_expr(actual, expected);
    }

    #[test]
    fn sub_op() {
        let actual = num(10).sub(text("abc"));
        let expected = "10 - 'abc'";
        test_expr(actual, expected);
    }

    ...
```

**Comment by panarch** [comment]
> 1. Make the order of Eq, Gt, etc match the order of BinaryOperator at ast::operator.

I'm also for this.

> 2. Divide the unit tests to different test methods and order them to match the order of BinaryOperator at ast::operator, like the format below.

However, the second one looks too much considering that each test case has too few info.
It would be little bit hard to recognize all splitted tests, `cargo test` usually runs parallelly and it does not ensure any order.

e.g. So, we can see that `ast_builder::expr::function::tests::function_*` unit tests are mixed with other tests.
After all the `ast_builder::function` impl are completed, then I'm considering to re-group tests.
```test ast_builder::expr::function::tests::function_trigonometrics ... ok```
`function_trigonometrics` would be a good example of grouping.

![image](https://user-images.githubusercontent.com/2025065/180783610-2b48df88-ecf6-48a4-8c17-ad7004568fb9.png)

**Comment by bugoverdose** [comment]
OK, I think it makes sense to group all the binary operation tests together. 
Then how about just reordering the tests inside the `binary_op` test method to match the order at `ast::operator`?

**Comment by panarch** [comment]
> Then how about just reordering the tests inside the binary_op test method to match the order at ast::operator
I'm really for this, good improvements to make it I think.
