### ISSUE TITLE
Rust version update - 1.62

### ISSUE THREAD

**Issue by 24seconds** [gluesql/gluesql#700]
## Description
While doing the #699 , I found that [rust version 1.62 is released](https://blog.rust-lang.org/2022/07/19/Rust-1.62.1.html) recently.

### clippy status
clippy seems to be [released 1.62.0](https://github.com/rust-lang/rust-clippy/releases/tag/rust-1.62.0)

### some clippy warnings
With 1.62 setting, I found some `clippy` warnings. It would be nice to resolve when updating the rust lang version
- macro related warnings
  - [github action link](https://github.com/24seconds/gluesql/runs/7596519405?check_suite_focus=true)
  - [clippy explanation](https://rust-lang.github.io/rust-clippy/master/index.html#crate_in_macro_def)
- unused lifetime
  - [github action link](https://github.com/24seconds/gluesql/runs/7596198969?check_suite_focus=true )

### note
I saw there is a good pr related to this - #564 .

**Comment by ChobobDev** [comment]
As I mentioned before, I will try to solve the following issue.
