### ISSUE TITLE
 'SingleQuotedString' is not accepted in inserts

### ISSUE THREAD

**Issue by willy610** [gluesql/gluesql#76]
Problem with insert of text.

Insert into  tableA values ("WORKS BUT NOT STANDARD" , 'STANDARD BUT IS NOT ACCEPTED');

Most exports from other databases uses SingleQuotedString. More Standard SQL.

Seems like expressions with SingleQuotedString works

**Comment by willy610** [comment]
I have tested/verified  corrections on a cloned repos.

How to proceed?

Create a new Branch?

Or await something from the community ?

**Comment by panarch** [comment]
You can fork this repository and then GitHub will make cloned repository, url may become https://github.com/willy610/gluesql
Then, work on that cloned repo. After that you can make pull request to this main repo, then I can review your code change.

This process is based on GitHub, so if you are familiar with git but not GitHub, then you may spend some time to get used to it.

* https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

This page above looks good to see.

**Comment by willy610** [comment]
It seems like the bug remains in the latest issue version = "0.1.16"

**Comment by panarch** [comment]
Yes, because no one takes this issue yet.
If you'd like to do this then you can add PR and I'll review and merge.

**Comment by willy610** [comment]
In ``glusql-main-3`` literals with SingleQuotedString is accepted but nothing is stored.
Works fine with double quote.
Perhaps some unit tests is to be introducde in ``/tests/basic.rs``

``INSERT INTO Test (id, num, name) VALUES (1,2,'Job'):``

``INSERT INTO Test (id, num, name) VALUES ;``

**Comment by willy610** [comment]
Of cource should be with escaped strings

``INSERT INTO Test (id, num, name) VALUES (3,4,'Job''s Macintosh');``

**Comment by KyGost** [comment]
Looks like it sorts itself out for every command but `INSERT`. Working on this now.

**Comment by KyGost** [comment]
#145

**Comment by KyGost** [comment]
@panarch close?

**Comment by panarch** [comment]
@KyGost Oh, thanks :) I'll close
