### ISSUE TITLE
Update `Expr::CompoundIdentifier` to have more accurate data format

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#768]
Currently, the format of `Expr::CompoundIdentifier(Vec<String>)` is a superset of what GlueSQL execution can handle it.
Only single pair of (table_alias, column_name) can exist, so the current shape `Vec<String>` is too broad.

We can consider to change the type of `Expr::CompoundIdentifier` to have more narrow info.
e.g.
```rust
Expr::AliasedIdentifier {
  alias: String,
  ident: String,
}
```

It would be nice that we can dicuss about this. @ever0de @devgony

**Comment by ever0de** [comment]
I agree. We discussed it verbally, but I was also thinking about it, and it seems to be the right way to go in the direction you wrote.
