### ISSUE TITLE
Valid Columntypes not checked at CREATE TABLE

### ISSUE THREAD

**Issue by willy610** [gluesql/gluesql#77]
CREATE TABLE foolish (first INTEGER, second ANYTHING_ACCEPTED);

Perhaps 
Checks in execute.rs 
fn prepare
and match Statement::CreateTable { name, columns, .. }

**Comment by panarch** [comment]
Thanks for reporting!
Currently, GlueSQL executor simply accept any kind of `Statement::CreateTable` enum from `sqlparser-rs`.

And it also looks... give us how to implement this kind of validation.
Maybe it's time to add a new module? `validator/`.

**Comment by KyGost** [comment]
Oh I didn't see this!
Fixed with #143

**Comment by panarch** [comment]
Oh, missing link.
It is now fixed in this pr! 👍 
https://github.com/gluesql/gluesql/pull/184
