### ISSUE TITLE
ORDER BY support

### ISSUE THREAD

**Issue by willy610** [gluesql/gluesql#78]
Hej,

Sorry for all issues. Not complaining. Love the SQL and in Rust!

But browsing into my swedish testdabase on recipes and it's categories
the output is not ordered on column 2.

(We have the same sort order in Swedish as in any Latin-1 countries)

"select * from category where categoryid > 50 order by 2;"
53	"Fläskkött"	""	
54	"Vegetarisk"	""	
55	"Pastej"	""	
56	"Gratäng"	""	
57	"Finskt"	""	
58	"Kassler"	""

**Comment by panarch** [comment]
That's welcome at all, and I'm so pleased about your reportings.

Let's simply rename this issue to "ORDER BY support"

`ORDER BY` is a type of query which may work best with index, but it still requires to work without index, too.
This issue is implementing `ORDER BY` without considering indexing stuff.

**Comment by willy610** [comment]
ORDER BY is an outer cover only useful for the presentation of result. Look into the AST ``Struct sqlparser::ast::Query`` A kind of sibling ``limit``

One can assume that the ordering mostly is on a subsets due to joins and where.

The location of an order by is probably in ``executor/execute.rs`` and after the ``select_with_labels``

I did an implementation of order by in the benchmark [https://github.com/willy610/abcsql.git](https://github.com/willy610/abcsql.gitl)

(Besides ORDER BY it holds a lot functionality)

It's very similar when using ``gluesql`` to take care of requests pattern
```
let storage = get_storage(how);
let mut glue = Glue::new(storage);
for query in parse(&one_query).unwrap() {
    match &glue.execute(&query).unwrap() {
        Select { labels, rows } => {
           let rows = orderby(labels.to_vec(), rows.to_vec(), &order_by);
           ...
```
The ``order by`` is like

1. Compile the AST order_by into columnnumber and ask/dsc
2. Insert each row in a ``BinaryHeap`` with ``Ord`` implementation using the compiled order_by
3. Retrieve the rows and return them

I think the ``orderby.rs`` can be adapted quit easily into ``executor/execute.rs``

**Comment by KyGost** [comment]
@willy610 
> I did an implementation of order by in the benchmark [https://github.com/willy610/abcsql.git](https://github.com/willy610/abcsql.gitl)
Did you do it on the GlueSQL side?
If so, could you share the code or put up a PR?

**Comment by willy610** [comment]
Hello
If you want to lock at how I did the ORDER BY

Look into the source of https://github.com/willy610/abcsql.git

You will find it in 

src/abcsql/applic_folder/orderby.rs

( called from src/abcsql/applic_folder/go_exec.rs )

Hope this will contribute to some implementation

Kindly
willy


> On 2021-02-27, at 12:23, Kyran Gostelow <notifications@github.com> wrote:
> 
> 
> @willy610
> 
> I did an implementation of order by in the benchmark https://github.com/willy610/abcsql.git
> 
> Did you do it on the GlueSQL side?
> If so, could you share the code or put up a PR?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-----------------------------
Willy Svenningsson
Johannas Vag 28
S-425 42 Hisings Karra
Sweden
+46 0768 22 20 26
willy@fager.st

**Comment by KyGost** [comment]
@willy610 
Thanks :-)
