### ISSUE TITLE
Impl `TryFrom<&Value> for usize`

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#789]
Location: [core/src/data/value/convert.rs](https://github.com/gluesql/gluesql/blob/main/core/src/data/value/convert.rs)

`TryFrom<&Value> for usize` would be useful for safe type casting from numeric literal to unsigned integer.

e.g. we can apply this to limit execution.
https://github.com/gluesql/gluesql/blob/06ba99eabcf38662c4fe85946b700a0f22b57b05/core/src/executor/limit.rs#L19-L24
```rust
let eval = |expr| -> Result<usize> {
    let value: Value = evaluate_stateless(None, expr)?.try_into()?;
    let n: i64 = value.try_into()?;


    Ok(n as usize)
};
```

**Comment by devgony** [comment]
i will handle this including `fetch.rs` !
