### ISSUE TITLE
Column names in Select results

### ISSUE THREAD

**Issue by willy610** [gluesql/gluesql#80]
Have made some programming around select in Rust
It's a little bit complicated and column names is missing I think.

In order to make gluesql competitive to (sqlite and mysql and more ) using (JS, C/C++, PHP, Java and more)
I think something like the following is required for Rust at least
(and C using gluesql. wow!)

1. Array of column names on payload

A: Usage is: iter over colnames in order to display them in order
B: Usage on whole row is: 'simple' item for all column values
C: Usage on columns in a row
I think it's important to get a value for a named column in a 'active row'
(From my own experience)

let value = get_value_from_column_named(colnam, some_context);

**Comment by panarch** [comment]
Related to https://github.com/gluesql/gluesql/issues/79

Interface would be like this,
```rust
let columns: Vec<String> = maybe_evaluate_columns(parsed_ast_from_sqlparser);
// accepted parsed ast from sqlparser and return Vec<String>
```

**Comment by willy610** [comment]
What about named columns in select
Missing ('select: Blend(FieldDefinitionNotSupported)')
Separate issue?

**Comment by panarch** [comment]
> What about named columns in select
> Missing ('select: Blend(FieldDefinitionNotSupported)')
> Separate issue?

That looks different one, can you also share the sql query you executed?

**Comment by willy610** [comment]
Of cource

modified last test in basics.rs
adding AS on a column

SELECT id AS SOMEALIASCOLUMNNAME, num FROM Test

cargo test --all-features
…
[Run] SELECT id AS SOMEALIASCOLUMNNAME, num FROM Test
thread 'basic' panicked at 'select: Blend(FieldDefinitionNotSupported)', /Users/willy/Documents/GitHub/gluesql/src/tests/basic.rs:43:79

Kindly,
willy

> On 2020-09-21, at 17:34, Taehoon Moon <notifications@github.com> wrote:
> 
> 
> What about named columns in select
> Missing ('select: Blend(FieldDefinitionNotSupported)')
> Separate issue?
> 
> That looks different one, can you also share the sql query you executed?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-----------------------------
Willy Svenningsson
Johannas Vag 28
S-425 42 Hisings Karra
Sweden
+46 0768 22 20 26
willy@fager.st

**Comment by panarch** [comment]
@willy610 Thanks! this is different issue but also required to support.
Thanks for reporting and I'll add via another issue.

**Comment by panarch** [comment]
input:
```sql
SELECT a, b as alias1, SUM(id) as summed FROM TableA;
```

output:
```rust
vec!["a", "alias1", "summed"]
```

**Comment by panarch** [comment]
Ok, let's use this issue #83
