### ISSUE TITLE
SELECT foo AS bar ... support,

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#82]
mentioned in https://github.com/gluesql/gluesql/issues/80

```sql
SELECT id AS SOMEALIASCOLUMNNAME, num FROM Test
```

Current [blend.rs](https://github.com/gluesql/gluesql/blob/main/src/executor/blend.rs) is not handling `AS`.
Simple fix, `blend` does not need to work on `AS` at all, just ignore `AS` and simply evaluate column expression.

**Comment by willy610** [comment]
Seems to having a solution in blend.rs as said above.
On both indents and expressions

```
SELECT ingredientid,ingredientid+2000 as PLUS2000 FROM ingredient 
WHERE energy > 500 
ORDER BY 1;

ingredientid    PLUS2000
15      2015
46      2046
128     2128
181     2181
253     2253
```

```
SELECT ingredientid AS NEWCOLNAME 
FROM   ingredient 
WHERE  ingredientname = 'mjölk';

NEWCOLNAME
169
```
