### ISSUE TITLE
[Function] Formatting `Time` Datatype

### ISSUE THREAD

**Issue by ChobobDev** [gluesql/gluesql#839]
While reviewing my previous work, I found out that there is a datatype `Time` in GlueSQL.
So I thought implementing the Format function for the following data type looked necessary.

Please let me know if I should have a go with the following issue.

My desirable changes are as follows
- [ ] Support `Time` data type in Format function
- [ ] Support String to `Time` Conversion 

The following issue should pass
```rust
        (
            r#"SELECT FORMAT(TIME "23:56:04","%H:%M") AS time"#,
            Ok(select!(
                time
                Str;
                "23:56".to_owned()
            )),
        ),

```
```rust
        (
            r#"SELECT TO_TIME("23:56:04","%H:%M:%S") AS time"#,
            Ok(select!(
                time
                Time;
                NaiveTime::from_hms(23, 56, 4)
            )),
        ),
```

Thank you

**Comment by devgony** [comment]
👍🏼 It would be nicer if there are sample SQLs and results in text body of Issue or PR

**Comment by ChobobDev** [comment]
I will add sample test cases ASAP 
Thank you
