### ISSUE TITLE
Implement `INITCAP` function

### ISSUE THREAD

**Issue by kim-seo-hyun** [gluesql/gluesql#864]
## Description
Add expression INITCAP.
INITCAP returns char, with the first letter of each word in uppercase, all other letters in lowercase.
Words are delimited by white space or characters that are not alphanumeric.
char can be of any of the data types CHAR, VARCHAR2, NCHAR, or NVARCHAR2. The return value is the same data type as char. 
``` sql

SELECT INITCAP('the soap') "Capitals"
  FROM DUAL; 

Capitals
---------
The Soap
```

ref : https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/INITCAP.html#GUID-9FE9E0EE-D6B6-4C2C-BDEF-4FF4E1314560

## Test to task

``` rs
"SELECT INITCAP(name) FROM Item;",
Ok(select!(
     "INITCAP(name)"
      Str              
     "Claire".to_owned()
     "Claire Kim".to_owned()
)),
```

## To do
- [ ] rename upper_lower to upper_lower_initcap 
- [ ] add test in upper_lower_initcap
- [ ] add initcap function

**Comment by panarch** [comment]
resolved in #1064
