### ISSUE TITLE
Result is not Send + Sync

### ISSUE THREAD

**Issue by OliverEvans96** [gluesql/gluesql#902]
Hello,

I've just started using this package in a small personal project. Thanks for all the work on this, I'm a big fan of GlueSQL so far.

It seems that the Result type is not Send + Sync, which prevents conversion to `anyhow::Result`. I think that the reason is that the `Storage` variant ([here](https://github.com/gluesql/gluesql/blob/main/core/src/result.rs#L29)) accepts any `dyn Error`.

I'd be interested to hear whether this was a considered decision, and whether it's important that it stay as it is. Otherwise, I would like to suggest changing this line to `dyn Error + Send + Sync`.

If this change is not possible, any other suggestions for converting to `anyhow::Error` would be appreciated.

Thanks!
Oliver

**Comment by OliverEvans96** [comment]
Here's my hacky workaround, if anyone is curious https://github.com/OliverEvans96/feet/blob/561b17ce9f28cc9600844b985d2efb672c589764/src/error.rs

**Comment by panarch** [comment]
Thanks really a lot for the suggestion!

> I'd be interested to hear whether this was a considered decision, and whether it's important that it stay as it is. Otherwise, I would like to suggest changing this line to dyn Error + Send + Sync.

There is no special reason not to add `Send + Sync` to `Error::Storage` variant.
And most of error objects basically satisfies `Send + Sync` so I am also for your suggestion to change Storage trait bounds from `dyn Error` to `dyn Error + Send + Sync` which can provide convenience to custom storage makers.

I will do quick fix on this issue, then you will be able to use `main` branch after merge for a while.
And in a few weeks there will be `v0.13` release :D
