### ISSUE TITLE
Merge `ColumnOption::{Null, NotNull}` into a single option

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#969]
There exists two `Null` and `NotNull` column options in GlueSQL's AST.
However, the information we only need is that the column is whether nullable or not.
We can consider to replace `ColumnOption::Null` and `ColumnOption:NotNull` to a single option `ColumnOption::Nullable`.

https://github.com/gluesql/gluesql/blob/79e88ac1c6ff307b7e79915f0932efafbf94927b/core/src/ast/ddl.rs#L38-L48

**Comment by devgony** [comment]
Looks like we can just add `nullable` field to `ColumnDef` like 
```rs
pub struct ColumnDef {
    pub name: String,
    pub data_type: DataType,
    pub options: Vec<ColumnOptionDef>,
    pub nullable: Nullable,
}

enum Nullable {
    Null,
    NotNull
}
```

**Comment by panarch** [comment]
Thanks that expanding `ColumnDef` looks certainly better!

**Comment by devgony** [comment]
And it would be nice to change default nullable from `NotNull` to `Null`;

**Comment by panarch** [comment]
> And it would be nice to change default nullable from `NotNull` to `Null`;

I agree but it would be good to work as a different PR.
