### ISSUE TITLE
Modify default ColumnOption from `NOT NULL` to `NULL`

### ISSUE THREAD

**Issue by devgony** [gluesql/gluesql#974]
## Issue
Currently, default ColumnOption is `NOT NULL` but many users would consider column as `NULL`
```sql
CREATE TABLE Foo (no INT);
```
| TABLE_NAME | COLUMN_NAME | NULLABLE |
|------------|-------------|-----------|
| Foo        | no          | NOT NULL         |
## Goal
To reduce confusion, Let's modify default ColumnOption from `NOT NULL` to `NULL`
```sql
CREATE TABLE Foo (no INT);
```
| TABLE_NAME | COLUMN_NAME | NULLABLE |
|------------|-------------|-----------|
| Foo        | no          | NULL         |

**Comment by MRGRAVITY817** [comment]
Looking forward to this update! This would simply the code from #629 .
