### ISSUE TITLE
[AST] Implement `HLL_COUNT` Function in AST

### ISSUE THREAD

**Issue by seonghun-dev** [gluesql/gluesql#975]
## Description

Add `HLL_COUNT` function in AST

```sql
select count(i), hll_count(i) from sequence;
```

`hll_count` function is approximate aggregate function. Approximate aggregation typically requires less memory than exact aggregation functions, but also introduces statistical error. 

Using HyperLogLog++ , Get Cardinality.
https://research.google/pubs/pub40671/

## Test
```rust
test_case!(hll_count, async move {

    test!(
        r#"select hll_count([0, 1, 1, 2, 3, 5]) as hll from Approx;"#,
        Ok(select!(
            column1
            I64;
            5
        ))
    );

});

```

## Refrence
https://cloud.google.com/bigquery/docs/reference/standard-sql/hll_functions
https://redis.io/commands/pfcount/
http://antirez.com/news/75
https://research.google/pubs/pub40671/
http://www.dmtcs.org/dmtcs-ojs/index.php/proceedings/article/view/dmAH0110
http://highscalability.com/blog/2012/4/5/big-data-counting-how-to-count-a-billion-distinct-objects-us.html
http://highlyscalable.wordpress.com/2012/05/01/probabilistic-structures-web-analytics-data-mining/
https://github.com/addthis/stream-lib/
http://en.wikipedia.org/wiki/Iterated_logarithm

**Comment by arbfay** [comment]
Hyperloglog is used for count distinct (which we've proposed to include in #970). 

I suggest that `COUNT(DISTINCT col)` becomes then `UNIQUE(col, hll, P)` with P as the precision of hll. This API would also be more welcoming to other count distinct algorithms in the future, such as probability counting or theta sketch.

There should be a default to "exact" though, so `UNIQUE(col)` should be translated to `COUNT(DISTINCT col)`) as hyperloglog and others are only used by people with very large, high cardinality datasets, which is probably not the case for most users of GlueSQL.

Is it ok if we merge this with #970 and include HLL as another count distinct algorithm?

**Comment by seonghun-dev** [comment]
I think the way you said it would be better for usability than this Issue. Thank you for the comments
